name: 'Wait for PR Checks'
description: 'Wait for all required PR checks to complete before merging'

inputs:
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  pr_number:
    description: 'PR number'
    required: true
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'GitHub App private key'
    required: true
  owner:
    description: 'Repository owner (organization or user)'
    required: true
  max_wait_time:
    description: 'Maximum time to wait in seconds (default: 3600)'
    required: false
    default: '3600'
  check_interval:
    description: 'Interval between checks in seconds (default: 30)'
    required: false
    default: '30'

outputs:
  checks_passed:
    description: 'Whether all checks passed (true/false)'
    value: ${{ steps.wait.outputs.checks_passed }}

runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ inputs.owner }}

    - name: Wait for PR checks to complete
      id: wait
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pr_number }}
        MAX_WAIT_TIME: ${{ inputs.max_wait_time }}
        CHECK_INTERVAL: ${{ inputs.check_interval }}
      run: |
        set +e
        
        echo "Waiting for PR #${PR_NUMBER} checks to complete..."
        ELAPSED=0
        
        while [ ${ELAPSED} -lt ${MAX_WAIT_TIME} ]; do
          # Get PR status including mergeable state and check runs
          PR_STATUS=$(gh pr view "${PR_NUMBER}" --repo "${GITHUB_REPOSITORY}" --json mergeable,mergeStateStatus,statusCheckRollup 2>&1)
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch PR status. Retrying..."
            sleep ${CHECK_INTERVAL}
            ELAPSED=$((ELAPSED + CHECK_INTERVAL))
            continue
          fi
          
          MERGEABLE=$(echo "${PR_STATUS}" | jq -r '.mergeable // false')
          MERGE_STATE=$(echo "${PR_STATUS}" | jq -r '.mergeStateStatus // "unknown"')
          
          # Check if PR is mergeable and all checks have passed
          if [ "${MERGEABLE}" = "true" ] && [ "${MERGE_STATE}" = "CLEAN" ]; then
            echo "✓ All checks passed. PR is ready to merge."
            echo "checks_passed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check if there are any failed checks
          if [ "${MERGEABLE}" = "false" ] && [ "${MERGE_STATE}" = "BLOCKED" ]; then
            echo "❌ PR checks failed or PR is blocked"
            echo "checks_passed=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          # Get check run status
          CHECK_RUNS=$(gh api repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/check-runs 2>&1)
          if [ $? -eq 0 ]; then
            TOTAL_CHECKS=$(echo "${CHECK_RUNS}" | jq '.total_count // 0')
            COMPLETED_CHECKS=$(echo "${CHECK_RUNS}" | jq '[.check_runs[] | select(.status == "completed")] | length')
            FAILED_CHECKS=$(echo "${CHECK_RUNS}" | jq '[.check_runs[] | select(.status == "completed" and .conclusion == "failure")] | length')
            
            if [ "${FAILED_CHECKS}" -gt 0 ]; then
              echo "❌ ${FAILED_CHECKS} check(s) failed"
              echo "${CHECK_RUNS}" | jq -r '.check_runs[] | select(.status == "completed" and .conclusion == "failure") | "  - \(.name): \(.conclusion)"'
              echo "checks_passed=false" >> $GITHUB_OUTPUT
              exit 1
            fi
            
            echo "Checks: ${COMPLETED_CHECKS}/${TOTAL_CHECKS} completed, waiting ${CHECK_INTERVAL}s... (${ELAPSED}s elapsed)"
          fi
          
          sleep ${CHECK_INTERVAL}
          ELAPSED=$((ELAPSED + CHECK_INTERVAL))
        done
        
        echo "Timeout waiting for PR checks to complete"
        echo "checks_passed=false" >> $GITHUB_OUTPUT
        exit 1

