name: 'Generate Metadata'
description: 'Generate platform and image tag from architecture and target info'

inputs:
  arch:
    description: 'Architecture (e.g., linux-amd64)'
    required: true
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  branch:
    description: 'Branch name'
    required: true
  version:
    description: 'Version string'
    required: true
  target_name:
    description: 'Target name'
    required: true
  sha_short:
    description: 'Short commit SHA (7 characters)'
    required: false
  pr_mode:
    description: 'Whether to use PR tag format (pr-<branch>-<version>-<sha>)'
    required: false
    default: 'false'

outputs:
  platform:
    description: 'Platform string (e.g., linux/amd64)'
    value: ${{ steps.metadata.outputs.platform }}
  image-tag:
    description: 'Full image tag'
    value: ${{ steps.metadata.outputs.image-tag }}

runs:
  using: 'composite'
  steps:
      - name: Validate inputs
        shell: bash
        run: |
          set -e
          set -o pipefail
          
          ACTION_NAME="generate-metadata"
          
          # Validate required inputs
          if [ -z "${{ inputs.arch }}" ] || [ "${{ inputs.arch }}" = "null" ] || [ "${{ inputs.arch }}" = "" ]; then
            echo "::error::[VALIDATION_001] ${ACTION_NAME}: arch is required" >&2
            exit 1
          fi
          
          if [ -z "${{ inputs.repository }}" ] || [ "${{ inputs.repository }}" = "null" ] || [ "${{ inputs.repository }}" = "" ]; then
            echo "::error::[VALIDATION_001] ${ACTION_NAME}: repository is required" >&2
            exit 1
          fi
          
          # Validate repository format (owner/repo)
          if ! [[ "${{ inputs.repository }}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
            echo "::error::[VALIDATION_004] ${ACTION_NAME}: Invalid repository format (expected: owner/repo)" >&2
            exit 1
          fi
          
          if [ -z "${{ inputs.branch }}" ] || [ "${{ inputs.branch }}" = "null" ] || [ "${{ inputs.branch }}" = "" ]; then
            echo "::error::[VALIDATION_001] ${ACTION_NAME}: branch is required" >&2
            exit 1
          fi
          
          if [ -z "${{ inputs.version }}" ] || [ "${{ inputs.version }}" = "null" ] || [ "${{ inputs.version }}" = "" ]; then
            echo "::error::[VALIDATION_001] ${ACTION_NAME}: version is required" >&2
            exit 1
          fi
          
          if [ -z "${{ inputs.target_name }}" ] || [ "${{ inputs.target_name }}" = "null" ] || [ "${{ inputs.target_name }}" = "" ]; then
            echo "::error::[VALIDATION_001] ${ACTION_NAME}: target_name is required" >&2
            exit 1
          fi
          
          # Conditional validation: sha_short is required when pr_mode is true
          if [ "${{ inputs.pr_mode }}" = "true" ]; then
            if [ -z "${{ inputs.sha_short }}" ] || [ "${{ inputs.sha_short }}" = "null" ] || [ "${{ inputs.sha_short }}" = "" ]; then
              echo "::error::[VALIDATION_008] ${ACTION_NAME}: sha_short is required when pr_mode is true" >&2
              exit 1
            fi
          fi
      
      - name: Generate metadata
        id: metadata
        shell: bash
        run: |
          ARCH="${{ inputs.arch }}"
          PLATFORM="${ARCH//linux-/linux/}"  # Replaces 'linux-' with 'linux/'
          
          # Sanitize branch name: replace '/' with '-' for valid Docker tag
          BRANCH="${{ inputs.branch }}"
          BRANCH_SANITIZED="${BRANCH//\//-}"
          
          # Determine tag format based on PR mode
          if [ "${{ inputs.pr_mode }}" = "true" ]; then
            # PR format: pr-<target_branch>-<version>-<sha_short>
            SHA_SHORT="${{ inputs.sha_short }}"
            IMAGE_TAG="ghcr.io/${{ inputs.repository }}:pr-${BRANCH_SANITIZED}-${{ inputs.version }}-${{ inputs.target_name }}-${SHA_SHORT}"
          else
            # Standard format: <branch>-<version>-<target_name>
            IMAGE_TAG="ghcr.io/${{ inputs.repository }}:${BRANCH_SANITIZED}-${{ inputs.version }}-${{ inputs.target_name }}"
          fi
          
          echo "platform=${PLATFORM}" >> $GITHUB_OUTPUT
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

