name: 'Validate Workflow Jobs'
description: 'Validate that all workflow jobs completed successfully, treating skipped jobs as passed'

inputs:
  job_results:
    description: 'JSON object mapping job names to their results (from needs context)'
    required: true

outputs:
  all_passed:
    description: 'Whether all jobs passed validation (true/false)'
    value: ${{ steps.validate.outputs.all_passed }}
  failed_jobs:
    description: 'JSON array of failed job names and results'
    value: ${{ steps.validate.outputs.failed_jobs }}

runs:
  using: 'composite'
  steps:
    - name: Validate all job results
      id: validate
      shell: bash
      env:
        JOB_RESULTS: ${{ inputs.job_results }}
      run: |
        set -e
        
        # Parse job results JSON
        if [ -z "${JOB_RESULTS}" ] || [ "${JOB_RESULTS}" = "null" ]; then
          echo "No job results provided"
          echo "all_passed=false" >> $GITHUB_OUTPUT
          echo "failed_jobs=[]" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # Process jobs and build arrays
        failed_jobs_json="[]"
        job_results_list=""
        
        # Iterate through job results from needs context
        # The needs context structure is: { "job_name": { "result": "success|failure|skipped|cancelled" } }
        job_names=$(echo "${JOB_RESULTS}" | jq -r 'keys[]')
        
        for job_name in ${job_names}; do
          job_result=$(echo "${JOB_RESULTS}" | jq -r ".[\"${job_name}\"].result // \"unknown\"")
          
          # Store job result for summary
          if [ -n "${job_results_list}" ]; then
            job_results_list="${job_results_list}\n"
          fi
          job_results_list="${job_results_list}${job_name}: ${job_result}"
          
          # Check if job failed (not success and not skipped)
          if [ "${job_result}" != "success" ] && [ "${job_result}" != "skipped" ]; then
            failed_job_json=$(echo "{\"name\":\"${job_name}\",\"result\":\"${job_result}\"}" | jq -c)
            failed_jobs_json=$(echo "${failed_jobs_json}" | jq -c ". + [${failed_job_json}]")
          fi
        done
        
        # Output summary
        echo "Job Results Summary:"
        echo -e "${job_results_list}" | sort | sed 's/^/  /'
        
        # Set outputs
        failed_count=$(echo "${failed_jobs_json}" | jq 'length')
        if [ "${failed_count}" -eq 0 ]; then
          all_passed="true"
        else
          all_passed="false"
        fi
        
        echo "all_passed=${all_passed}" >> $GITHUB_OUTPUT
        echo "failed_jobs=${failed_jobs_json}" >> $GITHUB_OUTPUT
        
        # Fail if any jobs failed
        if [ "${all_passed}" = "false" ]; then
          echo ""
          echo "❌ Validation failed - The following jobs did not complete successfully:"
          echo "${failed_jobs_json}" | jq -r '.[] | "  - \(.name): \(.result)"'
          exit 1
        else
          echo ""
          echo "✅ Validation passed - All executed jobs completed successfully"
        fi
