name: 'Create Git Tag'
description: 'Create and push a git tag with the version'

inputs:
  version:
    description: 'Version string for the tag'
    required: true
  sha:
    description: 'Commit SHA to tag'
    required: true
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  github_token:
    description: 'GitHub token (from GitHub App)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="create-git-tag"
        
        # Validate all required inputs
        if [ -z "${{ inputs.version }}" ] || [ "${{ inputs.version }}" = "null" ] || [ "${{ inputs.version }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: version is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.sha }}" ] || [ "${{ inputs.sha }}" = "null" ] || [ "${{ inputs.sha }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: sha is required" >&2
          exit 1
        fi
        
        # Validate SHA format (40 hex characters)
        if ! [[ "${{ inputs.sha }}" =~ ^[a-f0-9]{40}$ ]]; then
          echo "::error::[VALIDATION_003] ${ACTION_NAME}: Invalid sha format (expected: 40 hex characters)" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.repository }}" ] || [ "${{ inputs.repository }}" = "null" ] || [ "${{ inputs.repository }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: repository is required" >&2
          exit 1
        fi
        
        # Validate repository format (owner/repo)
        if ! [[ "${{ inputs.repository }}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
          echo "::error::[VALIDATION_004] ${ACTION_NAME}: Invalid repository format (expected: owner/repo)" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.github_token }}" ] || [ "${{ inputs.github_token }}" = "null" ] || [ "${{ inputs.github_token }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: github_token is required" >&2
          exit 1
        fi
        
        # Never log secret values
        echo "✓ GitHub token provided (not logged)"
    
    - name: Create and push git tag
      shell: bash
      run: |
        set -e
        
        VERSION="${{ inputs.version }}"
        SHA="${{ inputs.sha }}"
        REPOSITORY="${{ inputs.repository }}"
        
        TAG_NAME="v${VERSION}"
        
        echo "Creating tag: ${TAG_NAME} at commit ${SHA}"
        
        # Check if tag already exists
        if git rev-parse "${TAG_NAME}" >/dev/null 2>&1; then
          echo "Tag ${TAG_NAME} already exists. Skipping tag creation."
          exit 0
        fi
        
        # Create the tag
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "${TAG_NAME}" -m "Release version ${VERSION}" "${SHA}"
        
        # Push the tag
        echo "Pushing tag ${TAG_NAME}..."
        git push origin "${TAG_NAME}" || { echo "Error: Failed to push tag"; exit 1; }
        
        echo "✓ Successfully created and pushed tag ${TAG_NAME}"

