name: 'Extract PR Head SHA'
description: 'Extract PR head SHA from merge commit message using GitHub API'

inputs:
  commit_sha:
    description: 'Commit SHA to check'
    required: true

outputs:
  pr_head_sha:
    description: 'PR head SHA (full)'
    value: ${{ steps.extract.outputs.pr_head_sha }}
  pr_head_sha_short:
    description: 'PR head SHA (short, 7 characters)'
    value: ${{ steps.extract.outputs.pr_head_sha_short }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="extract-pr-head-sha"
        
        # Validate required input
        if [ -z "${{ inputs.commit_sha }}" ] || [ "${{ inputs.commit_sha }}" = "null" ] || [ "${{ inputs.commit_sha }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: commit_sha is required" >&2
          exit 1
        fi
        
        # Validate SHA format (40 hex characters)
        if ! [[ "${{ inputs.commit_sha }}" =~ ^[a-f0-9]{40}$ ]]; then
          echo "::error::[VALIDATION_003] ${ACTION_NAME}: Invalid commit_sha format (expected: 40 hex characters)" >&2
          exit 1
        fi
    
    - name: Extract PR head SHA
      id: extract
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -e
        
        COMMIT_SHA="${{ inputs.commit_sha }}"
        
        # Get commit message
        COMMIT_MSG=$(git log -1 --format='%B' "${COMMIT_SHA}" 2>/dev/null || echo "")
        
        # Extract PR number from commit message (format: "Merge pull request #123")
        PR_NUMBER=$(echo "${COMMIT_MSG}" | grep -oE 'Merge pull request #([0-9]+)' | grep -oE '[0-9]+' | head -1 || echo "")
        
        if [ -z "${PR_NUMBER}" ]; then
          # Try alternative format: "Merge #123" or "#123"
          PR_NUMBER=$(echo "${COMMIT_MSG}" | grep -oE '#([0-9]+)' | grep -oE '[0-9]+' | head -1 || echo "")
        fi
        
        PR_HEAD_SHA=""
        
        if [ -n "${PR_NUMBER}" ]; then
          echo "Found PR number in commit message: ${PR_NUMBER}"
          
          # Try to get PR head SHA using GitHub CLI first
          if command -v gh &> /dev/null; then
            PR_HEAD_SHA=$(gh pr view "${PR_NUMBER}" --json headShaOid --jq -r '.headShaOid' 2>/dev/null || echo "")
          fi
          
          # If GitHub CLI failed, try to extract from merge commit's second parent
          if [ -z "${PR_HEAD_SHA}" ]; then
            # Check if this is a merge commit (has second parent)
            if git rev-parse "${COMMIT_SHA}^2" >/dev/null 2>&1; then
              PR_HEAD_SHA=$(git rev-parse "${COMMIT_SHA}^2" 2>/dev/null || echo "")
              echo "Extracted PR head SHA from merge commit's second parent: ${PR_HEAD_SHA}"
            fi
          fi
          
          if [ -n "${PR_HEAD_SHA}" ]; then
            echo "PR head SHA: ${PR_HEAD_SHA}"
            PR_HEAD_SHA_SHORT="${PR_HEAD_SHA:0:7}"
            echo "PR head SHA (short): ${PR_HEAD_SHA_SHORT}"
            echo "pr_head_sha=${PR_HEAD_SHA}" >> $GITHUB_OUTPUT
            echo "pr_head_sha_short=${PR_HEAD_SHA_SHORT}" >> $GITHUB_OUTPUT
          else
            echo "Could not retrieve PR head SHA. Using merge commit SHA as fallback."
            echo "pr_head_sha=${COMMIT_SHA}" >> $GITHUB_OUTPUT
            echo "pr_head_sha_short=${COMMIT_SHA:0:7}" >> $GITHUB_OUTPUT
          fi
        else
          # Even without PR number, try to get second parent if it's a merge commit
          if git rev-parse "${COMMIT_SHA}^2" >/dev/null 2>&1; then
            PR_HEAD_SHA=$(git rev-parse "${COMMIT_SHA}^2" 2>/dev/null || echo "")
            if [ -n "${PR_HEAD_SHA}" ]; then
              echo "Extracted SHA from merge commit's second parent: ${PR_HEAD_SHA}"
              PR_HEAD_SHA_SHORT="${PR_HEAD_SHA:0:7}"
              echo "pr_head_sha=${PR_HEAD_SHA}" >> $GITHUB_OUTPUT
              echo "pr_head_sha_short=${PR_HEAD_SHA_SHORT}" >> $GITHUB_OUTPUT
            else
              echo "No PR number found and could not extract from merge commit. Using merge commit SHA as fallback."
              echo "pr_head_sha=${COMMIT_SHA}" >> $GITHUB_OUTPUT
              echo "pr_head_sha_short=${COMMIT_SHA:0:7}" >> $GITHUB_OUTPUT
            fi
          else
            echo "No PR number found in commit message. Using merge commit SHA as fallback."
            echo "pr_head_sha=${COMMIT_SHA}" >> $GITHUB_OUTPUT
            echo "pr_head_sha_short=${COMMIT_SHA:0:7}" >> $GITHUB_OUTPUT
          fi
        fi

