name: 'Smoke Test'
description: 'Run smoke test on Docker container image'

inputs:
  image:
    description: 'Docker image tag to test'
    required: true
  platform:
    description: 'Platform string (e.g., linux/amd64)'
    required: true
  package_version:
    description: 'Package version for log file naming'
    required: true
  test_url:
    description: 'Test URL endpoint to check (optional)'
    required: false

outputs:
  result:
    description: 'Test result: ok or nok'

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="smoke-test"
        
        # Validate all required inputs
        if [ -z "${{ inputs.image }}" ] || [ "${{ inputs.image }}" = "null" ] || [ "${{ inputs.image }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: image is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.platform }}" ] || [ "${{ inputs.platform }}" = "null" ] || [ "${{ inputs.platform }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: platform is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.package_version }}" ] || [ "${{ inputs.package_version }}" = "null" ] || [ "${{ inputs.package_version }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: package_version is required" >&2
          exit 1
        fi
    
    - name: Smoke Test
      id: smoketest
      shell: bash
      run: |
        set -e
        exitcode=0
        container_name="service-test-${{ inputs.package_version }}-${RANDOM}"
        
        # Create temporary config directory with proper permissions
        config_dir=$(mktemp -d)
        chmod 777 "${config_dir}"
        
        echo "Starting container: ${{ inputs.image }} on platform ${{ inputs.platform }}"
        docker run --platform="${{ inputs.platform }}" --network host -v "${config_dir}:/config" -d --name "${container_name}" "${{ inputs.image }}" || {
          echo "Failed to start container"
          rm -rf "${config_dir}"
          exit 1
        }
        
        # Wait a moment for container to initialize
        echo "Waiting for container to initialize..."
        sleep 5
        
        # Check if container is still running
        if ! docker ps | grep -q "${container_name}"; then
          echo "Container exited unexpectedly"
          docker logs "${container_name}" || true
          exit 1
        fi
        
        # Capture logs
        echo "Capturing container logs..."
        docker logs "${container_name}" > "${{ inputs.package_version }}-test.log" 2>&1 || true
        
        # Check logs for errors (basic check)
        echo "Checking container logs for errors..."
        ERROR_LINES=$(docker logs "${container_name}" 2>&1 | grep -i "error\|fatal\|panic" | head -5 || true)
        if [ -n "${ERROR_LINES}" ]; then
          echo "Warning: Found errors in container logs:"
          echo "${ERROR_LINES}"
          # Don't fail on warnings, but log them
        else
          echo "✓ No critical errors found in container logs"
        fi
        
        # Test URL endpoint if test_url is provided
        TEST_URL="${{ inputs.test_url }}"
        if [ -n "${TEST_URL}" ] && [ "${TEST_URL}" != "null" ] && [ "${TEST_URL}" != "" ]; then
          echo "Testing endpoint: ${TEST_URL}"
          if curl -fsSL --retry-all-errors --retry 60 --retry-max-time 120 -m 10 "${TEST_URL}" --output /dev/null; then
            echo "✓ Endpoint health check PASSED for ${TEST_URL}"
          else
            exitcode=$?
            echo "✗ Endpoint health check FAILED for ${TEST_URL} (exit code: ${exitcode})"
            echo "Container logs:"
            docker logs "${container_name}" || true
          fi
        else
          echo "No test_url provided in VERSION.json, skipping URL check"
        fi
        
        # Clean up container and temporary config directory
        echo "Cleaning up container..."
        docker stop "${container_name}" || true
        docker rm "${container_name}" || true
        
        # Set output and exit
        if [ ${exitcode} -eq 0 ]; then
          echo "result=ok" >> $GITHUB_OUTPUT
          echo "✓✓✓ Smoke test PASSED ✓✓✓"
        else
          echo "result=nok" >> $GITHUB_OUTPUT
          echo "✗✗✗ Smoke test FAILED (exit code: ${exitcode}) ✗✗✗"
        fi
        exit ${exitcode}

