name: 'Update Tags JSON'
description: 'Update tags.json file with new build tags and commit changes'

inputs:
  run_id:
    description: 'GitHub Actions run ID'
    required: true
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  server_url:
    description: 'GitHub server URL'
    required: true
  branch:
    description: 'Source branch name (for tags.json content and commit message)'
    required: true
  pr_base_branch:
    description: 'Branch to create PR against (default branch, usually main)'
    required: true
  version:
    description: 'Version string'
    required: true
  sha:
    description: 'Git commit SHA'
    required: true
  variants:
    description: 'Multiline string of variants'
    required: true
  github_token:
    description: 'GitHub token (from GitHub App)'
    required: true
  app_bot_name:
    description: 'GitHub App bot name (e.g., app-name[bot])'
    required: true
  app_bot_email:
    description: 'GitHub App bot email'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update tags.json and create PR
      id: create-pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        APP_BOT_NAME: ${{ inputs.app_bot_name }}
        APP_BOT_EMAIL: ${{ inputs.app_bot_email }}
      run: |
        set -e
        
        RUN_ID="${{ inputs.run_id }}"
        REPOSITORY="${{ inputs.repository }}"
        SERVER_URL="${{ inputs.server_url }}"
        BRANCH="${{ inputs.branch }}"
        PR_BASE_BRANCH="${{ inputs.pr_base_branch }}"
        VERSION="${{ inputs.version }}"
        SHA="${{ inputs.sha }}"
        VARIANTS="${{ inputs.variants }}"
        
        # Configure git credential helper for authentication (non-persistent)
        # Uses GH_TOKEN environment variable which is already set
        git config --global credential.helper '!f() { echo "username=x-access-token"; echo "password=${GH_TOKEN}"; }; f'
        
        # Set git user config globally BEFORE any git operations
        git config --global user.name "${APP_BOT_NAME}"
        git config --global user.email "${APP_BOT_EMAIL}"
        
        # Retry function for git operations
        retry_git_operation() {
          local max_attempts=3
          local attempt=1
          local wait_seconds=30
          
          while [ $attempt -le $max_attempts ]; do
            if [ $attempt -gt 1 ]; then
              echo "Retry attempt $attempt of $max_attempts (waiting ${wait_seconds}s)..."
              sleep $wait_seconds
              git pull --rebase || true
            fi
            
            if "$@"; then
              return 0
            fi
            
            attempt=$((attempt + 1))
          done
          
          echo "Failed after $max_attempts attempts"
          return 1
        }
        
        # Ensure we're on the base branch before creating new branch
        echo "Ensuring we're on base branch: ${PR_BASE_BRANCH}"
        git checkout "${PR_BASE_BRANCH}" || { echo "Error: Failed to checkout ${PR_BASE_BRANCH}"; exit 1; }
        git pull origin "${PR_BASE_BRANCH}" --rebase || { echo "Error: Failed to pull ${PR_BASE_BRANCH}"; exit 1; }
        
        # Create tags.json if it doesn't exist
        [ ! -f tags.json ] && echo '{}' > tags.json
        
        # Generate timestamp
        TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%S.000Z')
        BUILD_URL="${SERVER_URL}/${REPOSITORY}/actions/runs/${RUN_ID}"
        
        # Sanitize branch name: replace '/' with '-' for valid Docker tag (matching publish job)
        BRANCH_SANITIZED="${BRANCH//\//-}"
        
        # Update tags.json for each variant (matching publish job tag format)
        echo "$VARIANTS" | while IFS= read -r variant; do
          # Create tags matching publish job format: branch-variant, branch-version-variant, branch-sha-variant
          TAG_BRANCH_VARIANT="${BRANCH_SANITIZED}-${variant}"
          TAG_BRANCH_VERSION_VARIANT="${BRANCH_SANITIZED}-${VERSION}-${variant}"
          TAG_BRANCH_SHA_VARIANT="${BRANCH_SANITIZED}-${SHA:0:7}-${variant}"
          
          # Update tags.json using jq (same structure as publish job creates)
          jq --sort-keys \
              --arg branch_variant "${TAG_BRANCH_VARIANT}" \
              --arg tag_branch_variant "${TAG_BRANCH_VARIANT}" \
              --arg tag_branch_version_variant "${TAG_BRANCH_VERSION_VARIANT}" \
              --arg tag_branch_sha_variant "${TAG_BRANCH_SHA_VARIANT}" \
              --arg last_updated "${TIMESTAMP}" \
              --arg last_updated_url "${BUILD_URL}" \
              --arg description "${TAG_BRANCH_VARIANT}" \
              --argjson hide false \
              '.[$branch_variant] = {
                "description": $description,
                "hide": $hide,
                "last_updated": $last_updated,
                "last_updated_url": $last_updated_url,
                "tags": [$tag_branch_variant, $tag_branch_version_variant, $tag_branch_sha_variant]
              }' tags.json > tags.json.tmp && mv tags.json.tmp tags.json
        done
        
        # Initialize outputs to defaults
        echo "pr_created=false" >> $GITHUB_OUTPUT
        echo "pr_number=" >> $GITHUB_OUTPUT
        echo "pr_branch=" >> $GITHUB_OUTPUT
        
        # Only commit if tags.json actually changed
        if ! git diff --quiet tags.json; then
          git add tags.json
          git commit -m "Update tags.json for ${BRANCH} branch variants (version: ${VERSION}) [skip ci]" || exit 0
          
          # Create a unique branch for the PR
          BRANCH_TIMESTAMP=$(date +%s)
          PR_BRANCH="update-tags-json-${VERSION}-${BRANCH_TIMESTAMP}"
          
          echo "Creating branch: ${PR_BRANCH}"
          git checkout -b "${PR_BRANCH}" || { echo "Error: Failed to create branch"; exit 1; }
          
          # Push to the new branch
          echo "Pushing to branch: ${PR_BRANCH}"
          retry_git_operation git push -u origin "${PR_BRANCH}" || { echo "Error: Failed to push branch"; exit 1; }
          
          # Create PR
          PR_TITLE="update-tags-json-${BRANCH}-${VERSION}"
          PR_BODY="Automatically update tags.json for ${BRANCH} branch variants (version: ${VERSION})"
          
          echo "Creating PR: ${PR_TITLE}"
          
          # Use gh api to create PR and get number from JSON response
          PR_RESPONSE=$(gh api repos/${REPOSITORY}/pulls \
            --method POST \
            -f title="${PR_TITLE}" \
            -f body="${PR_BODY}" \
            -f base="${PR_BASE_BRANCH}" \
            -f head="${PR_BRANCH}" \
            2>&1)
          
          # Extract PR number from JSON response
          PR_NUMBER=$(echo "${PR_RESPONSE}" | jq -r '.number // empty' 2>/dev/null || echo "")
          
          if [ -z "${PR_NUMBER}" ] || [[ "${PR_NUMBER}" =~ ^[^0-9] ]] || [ "${PR_NUMBER}" = "null" ]; then
            echo "Failed to create PR. Response: ${PR_RESPONSE}"
            echo "pr_created=false" >> $GITHUB_OUTPUT
            echo "pr_number=" >> $GITHUB_OUTPUT
            echo "pr_branch=" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          echo "Created PR #${PR_NUMBER}"
          echo "pr_created=true" >> $GITHUB_OUTPUT
          echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "pr_branch=${PR_BRANCH}" >> $GITHUB_OUTPUT
        else
          echo "No changes to tags.json, skipping commit"
          echo "pr_created=false" >> $GITHUB_OUTPUT
          echo "pr_number=" >> $GITHUB_OUTPUT
          echo "pr_branch=" >> $GITHUB_OUTPUT
        fi

    - name: Auto merge PR
      id: auto-merge
      if: steps.create-pr.outputs.pr_created == 'true'
      uses: ./build-workflow/.github/actions/auto-merge-pr
      with:
        repository: ${{ inputs.repository }}
        pr_number: ${{ steps.create-pr.outputs.pr_number }}
        github_token: ${{ inputs.github_token }}
        app_bot_name: ${{ inputs.app_bot_name }}

    - name: Delete branch after merge
      id: delete-branch
      if: steps.auto-merge.outputs.merged == 'true'
      uses: ./build-workflow/.github/actions/delete-branch
      with:
        repository: ${{ inputs.repository }}
        branch_name: ${{ steps.create-pr.outputs.pr_branch }}
        github_token: ${{ inputs.github_token }}
