name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your use case and how this feature would be valuable.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? What should the feature do?
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Show how you would use this feature
      placeholder: |
        ```yaml
        # Example workflow configuration
        jobs:
          build:
            uses: runlix/build-workflow/.github/workflows/build-images-rebuild.yml@main
            with:
              new_feature: true
        ```
      render: yaml

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: "I considered using... but..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Workflow enhancement
        - Schema improvement
        - New input/output
        - Performance optimization
        - Documentation
        - Testing
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this require breaking changes to existing configurations?
      options:
        - "No - Backwards compatible"
        - "Yes - Breaking change"
        - "Maybe - Depends on implementation"
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: |
        - Service repositories could...
        - This would reduce...
        - This would enable...

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this feature?
      placeholder: |
        - Users affected: All / Some / New users only
        - Complexity: Low / Medium / High
        - Maintenance burden: Low / Medium / High

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use case
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Are you willing to contribute this feature?
      options:
        - "Yes - I can implement this"
        - "Maybe - With guidance"
        - "No - Suggestion only"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: "Similar features in other projects..."

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have clearly described the use case
          required: true
        - label: I have provided usage examples
          required: true
