name: 'Check Version Changed'
description: 'Check if version in VERSION.json changed between current commit and parent/base branch'

inputs:
  commit_sha:
    description: 'Current commit SHA to check'
    required: true
  branch:
    description: 'Branch name (base branch)'
    required: true
  default_branch:
    description: 'Default branch name'
    required: true

outputs:
  version_changed:
    description: 'Whether version changed (true/false)'
    value: ${{ steps.check.outputs.version_changed }}
  current_version:
    description: 'Current version from VERSION.json'
    value: ${{ steps.check.outputs.current_version }}
  previous_version:
    description: 'Previous version from parent/base branch'
    value: ${{ steps.check.outputs.previous_version }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="check-version-changed"
        
        # Validate all required inputs
        if [ -z "${{ inputs.commit_sha }}" ] || [ "${{ inputs.commit_sha }}" = "null" ] || [ "${{ inputs.commit_sha }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: commit_sha is required" >&2
          exit 1
        fi
        
        # Validate SHA format (40 hex characters)
        if ! [[ "${{ inputs.commit_sha }}" =~ ^[a-f0-9]{40}$ ]]; then
          echo "::error::[VALIDATION_003] ${ACTION_NAME}: Invalid commit_sha format (expected: 40 hex characters)" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.branch }}" ] || [ "${{ inputs.branch }}" = "null" ] || [ "${{ inputs.branch }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: branch is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.default_branch }}" ] || [ "${{ inputs.default_branch }}" = "null" ] || [ "${{ inputs.default_branch }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: default_branch is required" >&2
          exit 1
        fi
    
    - name: Check if version changed
      id: check
      shell: bash
      run: |
        set -e
        
        COMMIT_SHA="${{ inputs.commit_sha }}"
        BRANCH="${{ inputs.branch }}"
        DEFAULT_BRANCH="${{ inputs.default_branch }}"
        
        # Determine base branch for comparison
        # For merge commits, compare with the branch that was merged into
        BASE_BRANCH="${BRANCH}"
        if [ "${BRANCH}" = "${DEFAULT_BRANCH}" ]; then
          # If merging into default branch, compare with previous commit on that branch
          BASE_BRANCH="${DEFAULT_BRANCH}"
        fi
        
        echo "Checking version change for commit: ${COMMIT_SHA}"
        echo "Base branch: ${BASE_BRANCH}"
        
        # Check if VERSION.json exists in current commit
        if ! git show "${COMMIT_SHA}:VERSION.json" >/dev/null 2>&1; then
          echo "VERSION.json not found in current commit. Assuming version changed."
          echo "version_changed=true" >> $GITHUB_OUTPUT
          echo "current_version=" >> $GITHUB_OUTPUT
          echo "previous_version=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Extract current version
        CURRENT_VERSION=$(git show "${COMMIT_SHA}:VERSION.json" 2>/dev/null | jq -r '.version // empty' | grep -v "^null$" || echo "")
        
        if [ -z "${CURRENT_VERSION}" ]; then
          echo "Could not extract version from current commit's VERSION.json"
          echo "version_changed=false" >> $GITHUB_OUTPUT
          echo "current_version=" >> $GITHUB_OUTPUT
          echo "previous_version=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "Current version: ${CURRENT_VERSION}"
        echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
        
        # Get parent commit SHA
        # For merge commits, the first parent (^1) is the base branch HEAD before merge
        # For regular commits, ^1 is the direct parent
        PARENT_SHA=$(git rev-parse "${COMMIT_SHA}^1" 2>/dev/null || echo "")
        
        # Check if this is a merge commit (has second parent)
        if git rev-parse "${COMMIT_SHA}^2" >/dev/null 2>&1; then
          echo "Merge commit detected. Using first parent (base branch before merge): ${PARENT_SHA}"
        elif [ -n "${PARENT_SHA}" ]; then
          echo "Regular commit. Using parent: ${PARENT_SHA}"
        else
          echo "No parent commit found. This might be the initial commit."
          # Try to get the previous commit on the base branch (if it exists)
          PARENT_SHA=$(git rev-parse "${BASE_BRANCH}~1" 2>/dev/null || echo "")
          if [ -z "${PARENT_SHA}" ]; then
            echo "No previous commit found on base branch. Assuming first version."
          fi
        fi
        
        # Extract previous version
        PREVIOUS_VERSION=""
        if [ -n "${PARENT_SHA}" ]; then
          if git show "${PARENT_SHA}:VERSION.json" >/dev/null 2>&1; then
            PREVIOUS_VERSION=$(git show "${PARENT_SHA}:VERSION.json" 2>/dev/null | jq -r '.version // empty' | grep -v "^null$" || echo "")
          fi
        fi
        
        if [ -z "${PREVIOUS_VERSION}" ]; then
          echo "Previous version not found (first version or VERSION.json didn't exist). Assuming version changed."
          echo "version_changed=true" >> $GITHUB_OUTPUT
          echo "previous_version=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "Previous version: ${PREVIOUS_VERSION}"
        echo "previous_version=${PREVIOUS_VERSION}" >> $GITHUB_OUTPUT
        
        # Compare versions
        if [ "${CURRENT_VERSION}" != "${PREVIOUS_VERSION}" ]; then
          echo "Version changed: ${PREVIOUS_VERSION} -> ${CURRENT_VERSION}"
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version unchanged: ${CURRENT_VERSION}"
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi

