name: 'Prepare Build Args'
description: 'Prepare Docker build arguments from target and version info'

inputs:
  builder_tag:
    description: 'Builder image tag'
    required: false
  builder_digest:
    description: 'Builder image digest'
    required: false
  base_tag:
    description: 'Base image tag'
    required: false
  base_digest:
    description: 'Base image digest'
    required: false
  version:
    description: 'Version string'
    required: true
  build_date:
    description: 'Build date'
    required: false
  git_commit:
    description: 'Git commit SHA'
    required: true
  package_url:
    description: 'Package URL (optional)'
    required: false

outputs:
  build_args:
    description: 'Multiline build args string'

runs:
  using: 'composite'
  steps:
    - name: Prepare build args
      id: prepare-build-args
      shell: bash
      run: |
        # Validate that digests are provided (required for Docker FROM statements)
        # Docker FROM statements require digests to be non-empty to avoid invalid "tag@" format
        BUILDER_DIGEST_VALUE="${{ inputs.builder_digest }}"
        BASE_DIGEST_VALUE="${{ inputs.base_digest }}"
        
        if [ -z "${BUILDER_DIGEST_VALUE}" ] || [ "${BUILDER_DIGEST_VALUE}" = "null" ] || [ "${BUILDER_DIGEST_VALUE}" = "" ]; then
          echo "ERROR: BUILDER_DIGEST is required but was not provided or is empty"
          echo "  Received value: '${BUILDER_DIGEST_VALUE}'"
          exit 1
        fi
        if [ -z "${BASE_DIGEST_VALUE}" ] || [ "${BASE_DIGEST_VALUE}" = "null" ] || [ "${BASE_DIGEST_VALUE}" = "" ]; then
          echo "ERROR: BASE_DIGEST is required but was not provided or is empty"
          echo "  Received value: '${BASE_DIGEST_VALUE}'"
          exit 1
        fi
        
        # Build the build-args multiline string line by line to avoid indentation issues
        {
          if [ -n "${{ inputs.builder_tag }}" ] && [ "${{ inputs.builder_tag }}" != "null" ]; then
            echo "BUILDER_TAG=${{ inputs.builder_tag }}"
          fi
          echo "BUILDER_DIGEST=${BUILDER_DIGEST_VALUE}"
          if [ -n "${{ inputs.base_tag }}" ] && [ "${{ inputs.base_tag }}" != "null" ]; then
            echo "BASE_TAG=${{ inputs.base_tag }}"
          fi
          echo "BASE_DIGEST=${BASE_DIGEST_VALUE}"
          echo "VERSION=${{ inputs.version }}"
          if [ -n "${{ inputs.build_date }}" ] && [ "${{ inputs.build_date }}" != "null" ]; then
            echo "BUILD_DATE=${{ inputs.build_date }}"
          fi
          echo "GIT_COMMIT=${{ inputs.git_commit }}"
          
          # Conditionally add PACKAGE_URL if it exists
          if [ -n "${{ inputs.package_url }}" ] && [ "${{ inputs.package_url }}" != "null" ]; then
            echo "PACKAGE_URL=${{ inputs.package_url }}"
          fi
        } > /tmp/build_args.txt
        
        # #region agent log
        echo "DEBUG: Build args file contents:" >> /dev/stderr
        cat /tmp/build_args.txt >> /dev/stderr
        echo "DEBUG: BUILDER_DIGEST_VALUE=${BUILDER_DIGEST_VALUE}" >> /dev/stderr
        echo "DEBUG: BASE_DIGEST_VALUE=${BASE_DIGEST_VALUE}" >> /dev/stderr
        # #endregion
        
        # Output build args using multiline format (required for GitHub Actions multiline outputs)
        {
          echo 'build_args<<EOF'
          cat /tmp/build_args.txt
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        
        # #region agent log
        echo "DEBUG: GITHUB_OUTPUT build_args entry:" >> /dev/stderr
        grep -A 20 "^build_args" "$GITHUB_OUTPUT" | head -25 >> /dev/stderr || echo "DEBUG: build_args not found in GITHUB_OUTPUT" >> /dev/stderr
        # #endregion

