name: 'Prepare Build Args'
description: 'Prepare Docker build arguments from target and version info'

inputs:
  builder_tag:
    description: 'Builder image tag'
    required: false
  builder_digest:
    description: 'Builder image digest'
    required: false
  base_tag:
    description: 'Base image tag'
    required: false
  base_digest:
    description: 'Base image digest'
    required: false
  version:
    description: 'Version string'
    required: true
  build_date:
    description: 'Build date'
    required: false
  git_commit:
    description: 'Git commit SHA'
    required: true
  package_url:
    description: 'Package URL (optional)'
    required: false

outputs:
  build_args:
    description: 'Multiline build args string'

runs:
  using: 'composite'
  steps:
    - name: Prepare build args
      id: prepare-build-args
      shell: bash
      run: |
        # Build the build-args multiline string line by line to avoid indentation issues
        {
          if [ -n "${{ inputs.builder_tag }}" ] && [ "${{ inputs.builder_tag }}" != "null" ]; then
            echo "BUILDER_TAG=${{ inputs.builder_tag }}"
          fi
          if [ -n "${{ inputs.builder_digest }}" ] && [ "${{ inputs.builder_digest }}" != "null" ]; then
            echo "BUILDER_DIGEST=${{ inputs.builder_digest }}"
          fi
          if [ -n "${{ inputs.base_tag }}" ] && [ "${{ inputs.base_tag }}" != "null" ]; then
            echo "BASE_TAG=${{ inputs.base_tag }}"
          fi
          if [ -n "${{ inputs.base_digest }}" ] && [ "${{ inputs.base_digest }}" != "null" ]; then
            echo "BASE_DIGEST=${{ inputs.base_digest }}"
          fi
          echo "VERSION=${{ inputs.version }}"
          if [ -n "${{ inputs.build_date }}" ] && [ "${{ inputs.build_date }}" != "null" ]; then
            echo "BUILD_DATE=${{ inputs.build_date }}"
          fi
          echo "GIT_COMMIT=${{ inputs.git_commit }}"
          
          # Conditionally add PACKAGE_URL if it exists
          if [ -n "${{ inputs.package_url }}" ] && [ "${{ inputs.package_url }}" != "null" ]; then
            echo "PACKAGE_URL=${{ inputs.package_url }}"
          fi
        } > /tmp/build_args.txt
        
        # Output build args using multiline format (required for GitHub Actions multiline outputs)
        {
          echo 'build_args<<EOF'
          cat /tmp/build_args.txt
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

