name: 'Prepare Build Args'
description: 'Prepare Docker build arguments from target and version info'

inputs:
  builder_tag:
    description: 'Builder image tag'
    required: false
  builder_digest:
    description: 'Builder image digest'
    required: false
  base_tag:
    description: 'Base image tag'
    required: false
  base_digest:
    description: 'Base image digest'
    required: false
  version:
    description: 'Version string'
    required: true
  build_date:
    description: 'Build date'
    required: false
  git_commit:
    description: 'Git commit SHA'
    required: true
  package_url:
    description: 'Package URL (optional)'
    required: false

outputs:
  build_args:
    description: 'Multiline build args string'
    value: ${{ steps.prepare-build-args.outputs.build_args }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="prepare-build-args"
        
        # Validate required version input
        if [ -z "${{ inputs.version }}" ] || [ "${{ inputs.version }}" = "null" ] || [ "${{ inputs.version }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: version is required" >&2
          exit 1
        fi
        
        # Validate required git_commit input
        if [ -z "${{ inputs.git_commit }}" ] || [ "${{ inputs.git_commit }}" = "null" ] || [ "${{ inputs.git_commit }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: git_commit is required" >&2
          exit 1
        fi
        
        # Validate that digests are provided (required for Docker FROM statements)
        # Docker FROM statements require digests to be non-empty to avoid invalid "tag@" format
        BUILDER_DIGEST_VALUE="${{ inputs.builder_digest }}"
        BASE_DIGEST_VALUE="${{ inputs.base_digest }}"
        
        if [ -z "${BUILDER_DIGEST_VALUE}" ] || [ "${BUILDER_DIGEST_VALUE}" = "null" ] || [ "${BUILDER_DIGEST_VALUE}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: builder_digest is required" >&2
          exit 1
        fi
        if [ -z "${BASE_DIGEST_VALUE}" ] || [ "${BASE_DIGEST_VALUE}" = "null" ] || [ "${BASE_DIGEST_VALUE}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: base_digest is required" >&2
          exit 1
        fi
    
    - name: Prepare build args
      id: prepare-build-args
      shell: bash
      run: |
        BUILDER_DIGEST_VALUE="${{ inputs.builder_digest }}"
        BASE_DIGEST_VALUE="${{ inputs.base_digest }}"
        
        # Build the build-args multiline string line by line to avoid indentation issues
        {
          if [ -n "${{ inputs.builder_tag }}" ] && [ "${{ inputs.builder_tag }}" != "null" ]; then
            echo "BUILDER_TAG=${{ inputs.builder_tag }}"
          fi
          echo "BUILDER_DIGEST=${BUILDER_DIGEST_VALUE}"
          if [ -n "${{ inputs.base_tag }}" ] && [ "${{ inputs.base_tag }}" != "null" ]; then
            echo "BASE_TAG=${{ inputs.base_tag }}"
          fi
          echo "BASE_DIGEST=${BASE_DIGEST_VALUE}"
          echo "VERSION=${{ inputs.version }}"
          if [ -n "${{ inputs.build_date }}" ] && [ "${{ inputs.build_date }}" != "null" ]; then
            echo "BUILD_DATE=${{ inputs.build_date }}"
          fi
          echo "GIT_COMMIT=${{ inputs.git_commit }}"
          
          # Conditionally add PACKAGE_URL if it exists
          if [ -n "${{ inputs.package_url }}" ] && [ "${{ inputs.package_url }}" != "null" ]; then
            echo "PACKAGE_URL=${{ inputs.package_url }}"
          fi
        } > /tmp/build_args.txt
        
        # Output build args using multiline format (required for GitHub Actions multiline outputs)
        {
          echo 'build_args<<EOF'
          cat /tmp/build_args.txt
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

