name: 'Docker Setup and Login'
description: 'Set up Docker Buildx and login to GitHub Container Registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Registry username'
    required: false
  password:
    description: 'Registry password/token (from secrets)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="docker-setup-login"
        
        # Validate required password input
        if [ -z "${{ inputs.password }}" ] || [ "${{ inputs.password }}" = "null" ] || [ "${{ inputs.password }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: password is required" >&2
          exit 1
        fi
        
        # Never log the password value
        echo "✓ Password provided (not logged)"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3.12.0
    
    - name: Login to GHCR
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username || github.repository_owner }}
        password: ${{ inputs.password }}

