name: 'Extract Version Metadata'
description: 'Extract metadata from VERSION.json file'

inputs:
  extract_test_url:
    description: 'Whether to extract test_url field'
    required: false
    default: 'false'

outputs:
  version:
    description: 'Version string from VERSION.json'
  build_date:
    description: 'Build date from VERSION.json'
  branch:
    description: 'Current branch name'
  sha:
    description: 'Current commit SHA'
  default_branch:
    description: 'Default branch name'
  variants:
    description: 'Unique variants from enabled targets'
  matrix:
    description: 'JSON array of enabled targets'
  test_url:
    description: 'Test URL from VERSION.json (if extract_test_url is true)'

runs:
  using: 'composite'
  steps:
    - name: Extract metadata from VERSION.json
      id: extract
      shell: bash
      run: |
        # Debug: Check if VERSION.json exists
        if [ ! -f VERSION.json ]; then
          echo "ERROR: VERSION.json not found in current directory"
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
          exit 1
        fi
        
        # Debug: Check if jq is available
        if ! command -v jq &> /dev/null; then
          echo "ERROR: jq is not installed"
          exit 1
        fi
        
        # Extract version and build_date
        VERSION=$(jq -r '.version // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        BUILD_DATE=$(jq -r '.build_date // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        
        # Extract test_url if requested
        TEST_URL=""
        if [ "${{ inputs.extract_test_url }}" = "true" ]; then
          TEST_URL=$(jq -r '.test_url // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        fi
        
        # Extract enabled targets matrix
        MATRIX=$(jq '[ .targets[] | select(.enabled == true) ]' VERSION.json)
        
        # Ensure matrix is valid JSON (default to empty array if extraction failed)
        if [ -z "$MATRIX" ] || ! echo "$MATRIX" | jq . >/dev/null 2>&1; then
          echo "WARNING: Matrix extraction failed or invalid, defaulting to empty array"
          MATRIX="[]"
        fi
        
        # Debug: Check if matrix is empty
        if [ "$MATRIX" = "[]" ]; then
          echo "WARNING: No enabled targets found in VERSION.json"
        fi
        
        # Extract unique variants
        VARIANTS=$(jq -r '.targets[] | select(.enabled == true) | .variant' VERSION.json | sort -u)
        
        # GitHub context values
        BRANCH="${{ github.ref_name }}"
        SHA="${{ github.sha }}"
        DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
        
        # Debug: Print extracted values
        echo "Extracted values:"
        echo "  version: ${VERSION}"
        echo "  build_date: ${BUILD_DATE}"
        echo "  branch: ${BRANCH}"
        echo "  sha: ${SHA}"
        echo "  test_url: ${TEST_URL}"
        echo "  matrix: ${MATRIX}"
        echo "  variants: ${VARIANTS}"
        
        # Output all values
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
        echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
        echo "sha=${SHA}" >> $GITHUB_OUTPUT
        echo "default_branch=${DEFAULT_BRANCH}" >> $GITHUB_OUTPUT
        if [ "${{ inputs.extract_test_url }}" = "true" ]; then
          echo "test_url=${TEST_URL}" >> $GITHUB_OUTPUT
        fi
        {
          echo 'variants<<EOF'
          echo "$VARIANTS"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        # Set matrix output using EOF multiline format (required for large JSON outputs)
        # Write to temp file first to ensure proper formatting, then append to GITHUB_OUTPUT
        {
          echo 'matrix<<EOF'
          # Output the matrix JSON directly (jq already validated it's valid JSON)
          # Use printf to avoid any shell interpretation issues
          printf '%s\n' "$MATRIX"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        
        # Debug: Verify the output format
        echo "DEBUG: Matrix output written to GITHUB_OUTPUT"
        echo "DEBUG: Matrix JSON length: $(echo "$MATRIX" | wc -c) chars"
        
        # #region agent log
        echo '{"id":"log_'$(date +%s)'_extract","timestamp":'$(date +%s000)',"location":"extract-version-metadata/action.yml:117","message":"Matrix output written to GITHUB_OUTPUT","data":{"matrixLength":'$(echo "$MATRIX" | wc -c)',"matrixPreview":"'$(echo "$MATRIX" | head -c 100)'"},"sessionId":"debug-session","runId":"run1","hypothesisId":"A,B"}' >> /Users/ohayoun/personal/runlix/.cursor/debug.log
        # #endregion
        
        # Verify output was written correctly by reading it back
        if [ -f "$GITHUB_OUTPUT" ]; then
          # #region agent log
          echo '{"id":"log_'$(date +%s)'_extract2","timestamp":'$(date +%s000)',"location":"extract-version-metadata/action.yml:122","message":"Reading GITHUB_OUTPUT to verify matrix","data":{"fileExists":true,"hasMatrix":'$(grep -q "matrix" "$GITHUB_OUTPUT" && echo "true" || echo "false")'},"sessionId":"debug-session","runId":"run1","hypothesisId":"A,B"}' >> /Users/ohayoun/personal/runlix/.cursor/debug.log
          # #endregion
          echo "DEBUG: GITHUB_OUTPUT file exists, checking matrix entry"
          grep -A 10 "matrix" "$GITHUB_OUTPUT" | head -15 || echo "DEBUG: Matrix not found in GITHUB_OUTPUT"
        else
          # #region agent log
          echo '{"id":"log_'$(date +%s)'_extract3","timestamp":'$(date +%s000)',"location":"extract-version-metadata/action.yml:128","message":"GITHUB_OUTPUT file not found","data":{"fileExists":false},"sessionId":"debug-session","runId":"run1","hypothesisId":"A,B"}' >> /Users/ohayoun/personal/runlix/.cursor/debug.log
          # #endregion
          echo "ERROR: GITHUB_OUTPUT file not found"
        fi

