name: 'Extract Version Metadata'
description: 'Extract metadata from VERSION.json file'

inputs:
  extract_test_url:
    description: 'Whether to extract test_url field'
    required: false
    default: 'false'

outputs:
  version:
    description: 'Version string from VERSION.json'
  build_date:
    description: 'Build date from VERSION.json'
  branch:
    description: 'Current branch name'
  sha:
    description: 'Current commit SHA'
  default_branch:
    description: 'Default branch name'
  variants:
    description: 'Unique variants from enabled targets'
  matrix:
    description: 'JSON array of enabled targets'
  test_url:
    description: 'Test URL from VERSION.json (if extract_test_url is true)'

runs:
  using: 'composite'
  steps:
    - name: Extract metadata from VERSION.json
      id: extract
      shell: bash
      run: |
        # Debug: Check if VERSION.json exists
        if [ ! -f VERSION.json ]; then
          echo "ERROR: VERSION.json not found in current directory"
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
          exit 1
        fi
        
        # Debug: Check if jq is available
        if ! command -v jq &> /dev/null; then
          echo "ERROR: jq is not installed"
          exit 1
        fi
        
        # Extract version and build_date
        VERSION=$(jq -r '.version // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        BUILD_DATE=$(jq -r '.build_date // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        
        # Extract test_url if requested
        TEST_URL=""
        if [ "${{ inputs.extract_test_url }}" = "true" ]; then
          TEST_URL=$(jq -r '.test_url // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        fi
        
        # Extract enabled targets matrix
        MATRIX=$(jq '[ .targets[] | select(.enabled == true) ]' VERSION.json)
        
        # Ensure matrix is valid JSON (default to empty array if extraction failed)
        if [ -z "$MATRIX" ] || ! echo "$MATRIX" | jq . >/dev/null 2>&1; then
          echo "WARNING: Matrix extraction failed or invalid, defaulting to empty array"
          MATRIX="[]"
        fi
        
        # Debug: Check if matrix is empty
        if [ "$MATRIX" = "[]" ]; then
          echo "WARNING: No enabled targets found in VERSION.json"
        fi
        
        # Extract unique variants
        VARIANTS=$(jq -r '.targets[] | select(.enabled == true) | .variant' VERSION.json | sort -u)
        
        # GitHub context values
        BRANCH="${{ github.ref_name }}"
        SHA="${{ github.sha }}"
        DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
        
        # Debug: Print extracted values
        echo "Extracted values:"
        echo "  version: ${VERSION}"
        echo "  build_date: ${BUILD_DATE}"
        echo "  branch: ${BRANCH}"
        echo "  sha: ${SHA}"
        echo "  test_url: ${TEST_URL}"
        echo "  matrix: ${MATRIX}"
        echo "  variants: ${VARIANTS}"
        
        # Output all values
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
        echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
        echo "sha=${SHA}" >> $GITHUB_OUTPUT
        echo "default_branch=${DEFAULT_BRANCH}" >> $GITHUB_OUTPUT
        if [ "${{ inputs.extract_test_url }}" = "true" ]; then
          echo "test_url=${TEST_URL}" >> $GITHUB_OUTPUT
        fi
        {
          echo 'variants<<EOF'
          echo "$VARIANTS"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        # Debug: Verify matrix before outputting
        echo "DEBUG: Matrix before compacting:"
        echo "$MATRIX" | head -c 200
        echo ""
        
        {
          echo 'matrix<<EOF'
          # Use jq to compact the JSON and ensure it's valid
          # Store in variable first to avoid pipe issues with EOF format
          COMPACT_MATRIX=$(echo "$MATRIX" | jq -c '.')
          echo "DEBUG: Compact matrix length: ${#COMPACT_MATRIX}"
          echo "$COMPACT_MATRIX"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        
        # Debug: Verify output was set
        echo "DEBUG: Matrix output set, first 200 chars:"
        echo "$COMPACT_MATRIX" | head -c 200
        echo ""

