name: 'Extract Version Metadata'
description: 'Extract metadata from VERSION.json file'

inputs:
  extract_test_url:
    description: 'Whether to extract test_url field'
    required: false
    default: 'false'

outputs:
  version:
    description: 'Version string from VERSION.json'
    value: ${{ steps.extract.outputs.version }}
  build_date:
    description: 'Build date from VERSION.json'
    value: ${{ steps.extract.outputs.build_date }}
  branch:
    description: 'Current branch name'
    value: ${{ steps.extract.outputs.branch }}
  sha:
    description: 'Current commit SHA'
    value: ${{ steps.extract.outputs.sha }}
  sha_short:
    description: 'Short commit SHA (7 characters)'
    value: ${{ steps.extract.outputs.sha_short }}
  default_branch:
    description: 'Default branch name'
    value: ${{ steps.extract.outputs.default_branch }}
  variants:
    description: 'Unique variants from enabled targets'
    value: ${{ steps.extract.outputs.variants }}
  matrix:
    description: 'JSON array of enabled targets'
    value: ${{ steps.extract.outputs.matrix }}
  matrix_file:
    description: 'Path to filtered MATRIX.json file (only enabled targets)'
    value: ${{ steps.extract.outputs.matrix_file }}
  test_url:
    description: 'Test URL from VERSION.json (if extract_test_url is true)'
    value: ${{ steps.extract.outputs.test_url }}

runs:
  using: 'composite'
  steps:
    - name: Extract metadata from VERSION.json
      id: extract
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="extract-version-metadata"
        
        if [ ! -f VERSION.json ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: VERSION.json not found in current directory" >&2
          exit 1
        fi
        
        if ! command -v jq &> /dev/null; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: jq is not installed" >&2
          exit 1
        fi
        
        # Extract version and build_date
        VERSION=$(jq -r '.version // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        BUILD_DATE=$(jq -r '.build_date // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        
        # Extract test_url if requested
        TEST_URL=""
        if [ "${{ inputs.extract_test_url }}" = "true" ]; then
          TEST_URL=$(jq -r '.test_url // empty' VERSION.json 2>/dev/null | grep -v "^null$" || echo "")
        fi
        
        # Extract enabled targets matrix (compact JSON)
        MATRIX=$(jq -c '[ .targets[] | select(.enabled == true) ]' VERSION.json)
        
        # Ensure matrix is valid JSON (default to empty array if extraction failed)
        if [ -z "$MATRIX" ] || ! echo "$MATRIX" | jq . >/dev/null 2>&1; then
          echo "WARNING: Matrix extraction failed or invalid, defaulting to empty array"
          MATRIX="[]"
        fi
        
        # Create filtered MATRIX.json file with only enabled targets
        # This file can be used directly by downstream actions without filtering
        # Preserves root-level fields (version, build_date, sbranch, test_url) for context
        if ! jq '{version, build_date, sbranch, test_url, targets: [.targets[] | select(.enabled == true)]}' \
          VERSION.json > MATRIX.json 2>/dev/null; then
          echo "WARNING: Failed to create MATRIX.json, creating empty structure"
          echo '{"version":"","build_date":"","sbranch":"","test_url":"","targets":[]}' > MATRIX.json
        fi
        
        # Validate filtered file has at least one enabled target
        if ! jq -e '.targets | length > 0' MATRIX.json >/dev/null 2>&1; then
          echo "WARNING: No enabled targets found in MATRIX.json"
        fi
        
        # Extract unique variants
        VARIANTS=$(jq -r '.targets[] | select(.enabled == true) | .variant' VERSION.json | sort -u)
        
        # GitHub context values
        BRANCH="${{ github.ref_name }}"
        # For PRs, use the PR head SHA (actual commit on PR branch); otherwise use github.sha
        if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
          SHA="${{ github.event.pull_request.head.sha }}"
        else
          SHA="${{ github.sha }}"
        fi
        SHA_SHORT="${SHA:0:7}"
        DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
        
        # Output all values
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
        echo "build_date=${BUILD_DATE}" >> "$GITHUB_OUTPUT"
        echo "branch=${BRANCH}" >> "$GITHUB_OUTPUT"
        echo "sha=${SHA}" >> "$GITHUB_OUTPUT"
        echo "sha_short=${SHA_SHORT}" >> "$GITHUB_OUTPUT"
        echo "default_branch=${DEFAULT_BRANCH}" >> "$GITHUB_OUTPUT"
        if [ "${{ inputs.extract_test_url }}" = "true" ]; then
          echo "test_url=${TEST_URL}" >> "$GITHUB_OUTPUT"
        fi
        {
          echo 'variants<<EOF'
          echo "$VARIANTS"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        # Set matrix output using multiline EOF format for large JSON outputs
        {
          echo 'matrix<<EOF'
          printf '%s\n' "$MATRIX"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        
        # Output matrix file path for downstream actions
        echo "matrix_file=MATRIX.json" >> "$GITHUB_OUTPUT"

