name: 'Check PR Commit'
description: 'Check if commit was made by github-actions[bot] and get PR title if available'

inputs:
  commit_sha:
    description: 'Commit SHA to check'
    required: true

outputs:
  is_automated:
    description: 'Whether commit was made by github-actions[bot]'
    value: ${{ steps.check.outputs.is_automated }}
  pr_title:
    description: 'PR title if commit is from a merged PR'
    value: ${{ steps.check.outputs.pr_title }}
  should_tag:
    description: 'Whether a git tag should be created (true if update-version- PR)'
    value: ${{ steps.check.outputs.should_tag }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="check-pr-commit"
        
        # Validate required input
        if [ -z "${{ inputs.commit_sha }}" ] || [ "${{ inputs.commit_sha }}" = "null" ] || [ "${{ inputs.commit_sha }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: commit_sha is required" >&2
          exit 1
        fi
        
        # Validate SHA format (40 hex characters)
        if ! [[ "${{ inputs.commit_sha }}" =~ ^[a-f0-9]{40}$ ]]; then
          echo "::error::[VALIDATION_003] ${ACTION_NAME}: Invalid commit_sha format (expected: 40 hex characters)" >&2
          exit 1
        fi
    
    - name: Check commit author and PR info
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -e
        
        COMMIT_SHA="${{ inputs.commit_sha }}"
        
        # Get commit author info
        COMMIT_AUTHOR=$(git log -1 --format='%an' "${COMMIT_SHA}" 2>/dev/null || echo "")
        COMMIT_EMAIL=$(git log -1 --format='%ae' "${COMMIT_SHA}" 2>/dev/null || echo "")
        
        echo "Commit author: ${COMMIT_AUTHOR}"
        echo "Commit email: ${COMMIT_EMAIL}"
        
        # Check if commit was made by github-actions[bot]
        if [ "${COMMIT_AUTHOR}" != "github-actions[bot]" ] || [ "${COMMIT_EMAIL}" != "github-actions[bot]@users.noreply.github.com" ]; then
          echo "Commit was not made by github-actions[bot]. Skipping PR check."
          echo "is_automated=false" >> $GITHUB_OUTPUT
          echo "pr_title=" >> $GITHUB_OUTPUT
          echo "should_tag=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "is_automated=true" >> $GITHUB_OUTPUT
        
        # Try to find the PR that was merged (check commit message and GitHub API)
        # First, check if commit message contains PR number
        COMMIT_MSG=$(git log -1 --format='%B' "${COMMIT_SHA}" 2>/dev/null || echo "")
        
        # Extract PR number from commit message (format: "Merge pull request #123")
        PR_NUMBER=$(echo "${COMMIT_MSG}" | grep -oE 'Merge pull request #([0-9]+)' | grep -oE '[0-9]+' | head -1 || echo "")
        
        if [ -z "${PR_NUMBER}" ]; then
          # Try alternative format: "Merge #123" or "#123"
          PR_NUMBER=$(echo "${COMMIT_MSG}" | grep -oE '#([0-9]+)' | grep -oE '[0-9]+' | head -1 || echo "")
        fi
        
        if [ -n "${PR_NUMBER}" ]; then
          echo "Found PR number in commit message: ${PR_NUMBER}"
          
          # Get PR title using GitHub CLI
          if command -v gh &> /dev/null; then
            PR_TITLE=$(gh pr view "${PR_NUMBER}" --json title --jq -r '.title' 2>/dev/null || echo "")
            
            if [ -n "${PR_TITLE}" ]; then
              echo "PR title: ${PR_TITLE}"
              echo "pr_title=${PR_TITLE}" >> $GITHUB_OUTPUT
              
              # Check if PR title starts with "update-version-"
              if [[ "${PR_TITLE}" =~ ^update-version- ]]; then
                echo "PR title starts with 'update-version-'. Tag should be created."
                echo "should_tag=true" >> $GITHUB_OUTPUT
              else
                echo "PR title does not start with 'update-version-'. No tag needed."
                echo "should_tag=false" >> $GITHUB_OUTPUT
              fi
            else
              echo "Could not retrieve PR title. Assuming no tag needed."
              echo "pr_title=" >> $GITHUB_OUTPUT
              echo "should_tag=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "GitHub CLI not available. Cannot retrieve PR title."
            echo "pr_title=" >> $GITHUB_OUTPUT
            echo "should_tag=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "No PR number found in commit message. Assuming no tag needed."
          echo "pr_title=" >> $GITHUB_OUTPUT
          echo "should_tag=false" >> $GITHUB_OUTPUT
        fi

