name: 'Delete Branch'
description: 'Delete a branch after PR merge'

inputs:
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  branch_name:
    description: 'Branch name to delete'
    required: true
  github_token:
    description: 'GitHub token (from GitHub App)'
    required: true

outputs:
  deleted:
    description: 'Whether the branch was deleted (true/false)'
    value: ${{ steps.delete-branch.outputs.deleted }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="delete-branch"
        
        # Validate all required inputs
        if [ -z "${{ inputs.repository }}" ] || [ "${{ inputs.repository }}" = "null" ] || [ "${{ inputs.repository }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: repository is required" >&2
          exit 1
        fi
        
        # Validate repository format (owner/repo)
        if ! [[ "${{ inputs.repository }}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
          echo "::error::[VALIDATION_004] ${ACTION_NAME}: Invalid repository format (expected: owner/repo)" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.branch_name }}" ] || [ "${{ inputs.branch_name }}" = "null" ] || [ "${{ inputs.branch_name }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: branch_name is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.github_token }}" ] || [ "${{ inputs.github_token }}" = "null" ] || [ "${{ inputs.github_token }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: github_token is required" >&2
          exit 1
        fi
        
        # Never log secret values
        echo "✓ GitHub token provided (not logged)"
    
    - name: Delete branch
      id: delete-branch
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        REPOSITORY: ${{ inputs.repository }}
      run: |
        set -e
        
        echo "Deleting branch: ${BRANCH_NAME}"
        # Use gh CLI to delete the branch
        if gh api repos/${REPOSITORY}/git/refs/heads/${BRANCH_NAME} --method DELETE 2>&1; then
          echo "deleted=true" >> $GITHUB_OUTPUT
          echo "✓ Successfully deleted branch ${BRANCH_NAME}"
        else
          EXIT_CODE=$?
          # Check if branch still exists (might have been deleted already or doesn't exist)
          BRANCH_CHECK=$(gh api repos/${REPOSITORY}/git/refs/heads/${BRANCH_NAME} 2>&1 || echo "NOT_FOUND")
          if echo "${BRANCH_CHECK}" | grep -q "Not Found\|404"; then
            echo "Branch ${BRANCH_NAME} was already deleted or doesn't exist"
            echo "deleted=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Failed to delete branch (exit code: ${EXIT_CODE})"
          echo "deleted=false" >> $GITHUB_OUTPUT
          exit ${EXIT_CODE}
        fi

