name: 'Auto Merge PR'
description: 'Automatically merge PRs created by the GitHub App bot with titles starting with "update-digests", "update-version-", or "update-tags-json-"'

inputs:
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  pr_number:
    description: 'PR number'
    required: true
  github_token:
    description: 'GitHub token (from GitHub App)'
    required: true
  app_bot_name:
    description: 'GitHub App bot name (e.g., app-name[bot])'
    required: true

outputs:
  merged:
    description: 'Whether the PR was merged (true/false)'
    value: ${{ steps.auto-merge.outputs.merged }}

runs:
  using: 'composite'
  steps:
    - name: Check PR conditions and merge
      id: auto-merge
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        APP_BOT_NAME: ${{ inputs.app_bot_name }}
      run: |
        set -e
        
        REPOSITORY="${{ inputs.repository }}"
        PR_NUMBER="${{ inputs.pr_number }}"
        
        # Get PR details from GitHub API
        echo "Fetching PR #${PR_NUMBER} details from ${REPOSITORY}..."
        PR_DATA=$(gh api repos/${REPOSITORY}/pulls/${PR_NUMBER} || echo "")
        
        if [ -z "${PR_DATA}" ]; then
          echo "Failed to fetch PR data. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Extract PR author, type, and title
        PR_AUTHOR=$(echo "${PR_DATA}" | jq -r '.user.login // ""')
        PR_AUTHOR_TYPE=$(echo "${PR_DATA}" | jq -r '.user.type // ""')
        PR_TITLE=$(echo "${PR_DATA}" | jq -r '.title // ""')
        
        echo "PR details:"
        echo "  Author: ${PR_AUTHOR}"
        echo "  Author Type: ${PR_AUTHOR_TYPE}"
        echo "  Title: ${PR_TITLE}"
        echo "  Number: ${PR_NUMBER}"
        echo "  Expected bot: ${APP_BOT_NAME}"
        
        # Check if PR author is the GitHub App bot
        if [ "${PR_AUTHOR}" != "${APP_BOT_NAME}" ]; then
          echo "PR author is '${PR_AUTHOR}', not '${APP_BOT_NAME}'. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if PR author type is Bot
        if [ "${PR_AUTHOR_TYPE}" != "Bot" ]; then
          echo "PR author type is '${PR_AUTHOR_TYPE}', not 'Bot'. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if PR title starts with "update-digests", "update-version-", or "update-tags-json-"
        if [[ ! "${PR_TITLE}" =~ ^update-digests ]] && \
           [[ ! "${PR_TITLE}" =~ ^update-version- ]] && \
           [[ ! "${PR_TITLE}" =~ ^update-tags-json- ]]; then
          echo "PR title '${PR_TITLE}' does not start with 'update-digests', 'update-version-', or 'update-tags-json-'. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "✓ All PR conditions met"

        # Check if PR is still open
        PR_STATE=$(gh pr view "${PR_NUMBER}" --repo "${REPOSITORY}" --json state -q '.state' 2>&1 || echo "ERROR")
        if [ "${PR_STATE}" = "ERROR" ]; then
          echo "Failed to check PR state. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        if [ "${PR_STATE}" != "OPEN" ]; then
          echo "PR is not open (state: ${PR_STATE}). Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if PR is mergeable before attempting merge
        MERGEABLE=$(gh pr view "${PR_NUMBER}" --repo "${REPOSITORY}" --json mergeable -q '.mergeable // "UNKNOWN"' 2>&1 || echo "UNKNOWN")
        if [ "${MERGEABLE}" != "MERGEABLE" ]; then
          echo "PR is not mergeable (mergeable: ${MERGEABLE}). Skipping merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Merge the PR directly using merge commits (checks have already passed)
        echo "Merging PR #${PR_NUMBER}..."
        if gh pr merge "${PR_NUMBER}" --repo "${REPOSITORY}" --auto --merge --delete-branch=true; then
          echo "merged=true" >> $GITHUB_OUTPUT
          echo "✓ Successfully merged PR #${PR_NUMBER}"
        else
          EXIT_CODE=$?
          echo "Failed to merge PR (exit code: ${EXIT_CODE})"
          # Check if PR was already merged
          CURRENT_STATE=$(gh pr view "${PR_NUMBER}" --repo "${REPOSITORY}" --json state -q '.state' 2>&1 || echo "ERROR")
          if [ "${CURRENT_STATE}" = "MERGED" ]; then
            echo "PR was already merged. This is not an error."
            echo "merged=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "merged=false" >> $GITHUB_OUTPUT
          exit ${EXIT_CODE}
        fi

