name: 'Auto Merge PR'
description: 'Automatically merge PRs created by the GitHub App bot with titles starting with "update-digests" or "update-version-"'

inputs:
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  pr_number:
    description: 'PR number'
    required: true

outputs:
  merged:
    description: 'Whether the PR was merged (true/false)'
    value: ${{ steps.auto-merge.outputs.merged }}

runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.RUNLIX_APP_ID }}
        private-key: ${{ secrets.RUNLIX_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Get GitHub App Bot User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Check PR conditions and merge
      id: auto-merge
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        APP_BOT_NAME: ${{ steps.app-token.outputs.app-slug }}[bot]
        APP_BOT_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com
      run: |
        set -e
        
        REPOSITORY="${{ inputs.repository }}"
        PR_NUMBER="${{ inputs.pr_number }}"
        
        # Get PR details from GitHub API
        echo "Fetching PR #${PR_NUMBER} details from ${REPOSITORY}..."
        PR_DATA=$(gh api repos/${REPOSITORY}/pulls/${PR_NUMBER} || echo "")
        
        if [ -z "${PR_DATA}" ]; then
          echo "Failed to fetch PR data. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Extract PR author and title
        PR_AUTHOR=$(echo "${PR_DATA}" | jq -r '.user.login // ""')
        PR_TITLE=$(echo "${PR_DATA}" | jq -r '.title // ""')
        
        echo "PR details:"
        echo "  Author: ${PR_AUTHOR}"
        echo "  Title: ${PR_TITLE}"
        echo "  Number: ${PR_NUMBER}"
        echo "  Expected bot: ${APP_BOT_NAME}"
        
        # Check if PR author is the GitHub App bot
        if [ "${PR_AUTHOR}" != "${APP_BOT_NAME}" ]; then
          echo "PR author is '${PR_AUTHOR}', not '${APP_BOT_NAME}'. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get PR author email from commits (most reliable for bot PRs)
        PR_AUTHOR_EMAIL=$(gh api repos/${REPOSITORY}/pulls/${PR_NUMBER}/commits --jq '.[0].commit.author.email // ""' | head -1 || echo "")
        
        # Fallback: try PR user object email
        if [ -z "${PR_AUTHOR_EMAIL}" ]; then
          PR_AUTHOR_EMAIL=$(echo "${PR_DATA}" | jq -r '.user.email // ""')
        fi
        
        # Fallback: try user profile email
        if [ -z "${PR_AUTHOR_EMAIL}" ]; then
          PR_AUTHOR_EMAIL=$(gh api users/${PR_AUTHOR} --jq '.email // ""' || echo "")
        fi
        
        echo "  Author Email: ${PR_AUTHOR_EMAIL}"
        echo "  Expected email: ${APP_BOT_EMAIL}"
        
        # Check if PR author email matches expected email
        if [ "${PR_AUTHOR_EMAIL}" != "${APP_BOT_EMAIL}" ]; then
          echo "PR author email is '${PR_AUTHOR_EMAIL}', not '${APP_BOT_EMAIL}'. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if PR title starts with "update-digests" or "update-version-"
        if [[ ! "${PR_TITLE}" =~ ^update-digests ]] && [[ ! "${PR_TITLE}" =~ ^update-version- ]]; then
          echo "PR title '${PR_TITLE}' does not start with 'update-digests' or 'update-version-'. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "✓ All PR conditions met"
        
        # Check if PR is still open
        PR_STATE=$(gh pr view "${PR_NUMBER}" --repo "${REPOSITORY}" --json state -q '.state' 2>&1 || echo "ERROR")
        if [ "${PR_STATE}" = "ERROR" ]; then
          echo "Failed to check PR state. Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        if [ "${PR_STATE}" != "OPEN" ]; then
          echo "PR is not open (state: ${PR_STATE}). Skipping auto-merge."
          echo "merged=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Merge the PR
        echo "Merging PR #${PR_NUMBER}..."
        if gh pr merge "${PR_NUMBER}" --repo "${REPOSITORY}" --merge --auto; then
          echo "merged=true" >> $GITHUB_OUTPUT
          echo "✓ Successfully merged PR #${PR_NUMBER}"
        else
          EXIT_CODE=$?
          echo "Failed to merge PR (exit code: ${EXIT_CODE})"
          # Check if PR was already merged
          CURRENT_STATE=$(gh pr view "${PR_NUMBER}" --repo "${REPOSITORY}" --json state -q '.state' 2>&1 || echo "ERROR")
          if [ "${CURRENT_STATE}" = "MERGED" ]; then
            echo "PR was already merged. This is not an error."
            echo "merged=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "merged=false" >> $GITHUB_OUTPUT
          exit ${EXIT_CODE}
        fi

