name: 'Check PR Images Exist'
description: |
  Checks if PR images exist in GitHub Container Registry (GHCR) by verifying all target images.
  
  This action checks all targets in the matrix to ensure all PR images exist. The image tag format is:
  ghcr.io/{repository}:pr-{branch}-{version}-{target}-{sha}

inputs:
  repository:
    description: 'GitHub repository in owner/repo format (e.g., runlix/radarr)'
    required: true
  branch:
    description: 'Branch name (will be sanitized: slashes replaced with hyphens)'
    required: true
  version:
    description: 'Version string from VERSION.json'
    required: true
  pr_head_sha_short:
    description: 'PR head commit SHA shortened to 7 hex characters (e.g., 9e4b4f2)'
    required: true
  matrix_file:
    description: 'Path to filtered MATRIX.json file (only enabled targets). Defaults to MATRIX.json'
    required: false
    default: 'MATRIX.json'

outputs:
  pr_images_found:
    description: 'true if all PR images exist for all targets, false otherwise'
    value: ${{ steps.check.outputs.pr_images_found }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        readonly ACTION_NAME="check-pr-images-exist"
        
        # Helper function: Validate required input
        validate_required() {
          local name="$1"
          local value="$2"
          if [ -z "${value}" ] || [ "${value}" = "null" ]; then
            echo "::error::[VALIDATION_001] ${ACTION_NAME}: ${name} is required" >&2
            exit 1
          fi
        }
        
        # Helper function: Validate repository format
        validate_repository() {
          local repo="$1"
          if ! [[ "${repo}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
            echo "::error::[VALIDATION_002] ${ACTION_NAME}: Invalid repository format (expected: owner/repo, got: ${repo})" >&2
            exit 1
          fi
        }
        
        # Helper function: Validate SHA format
        validate_sha() {
          local sha="$1"
          if ! [[ "${sha}" =~ ^[a-f0-9]{7}$ ]]; then
            echo "::error::[VALIDATION_003] ${ACTION_NAME}: Invalid pr_head_sha_short format (expected: 7 lowercase hex characters, got: ${sha})" >&2
            exit 1
          fi
        }
        
        # Extract inputs
        REPOSITORY_INPUT="${{ inputs.repository }}"
        BRANCH_INPUT="${{ inputs.branch }}"
        VERSION_INPUT="${{ inputs.version }}"
        PR_HEAD_SHA_SHORT_INPUT="${{ inputs.pr_head_sha_short }}"
        
        # Validate all inputs
        validate_required "repository" "${REPOSITORY_INPUT}"
        validate_required "branch" "${BRANCH_INPUT}"
        validate_required "version" "${VERSION_INPUT}"
        validate_required "pr_head_sha_short" "${PR_HEAD_SHA_SHORT_INPUT}"
        
        validate_repository "${REPOSITORY_INPUT}"
        validate_sha "${PR_HEAD_SHA_SHORT_INPUT}"
        
        # Validate matrix file exists and is readable
        # Matrix file is pre-validated by extract-version-metadata, so we just check it exists
        MATRIX_FILE="${{ inputs.matrix_file }}"
        if [ -z "${MATRIX_FILE}" ]; then
          MATRIX_FILE="MATRIX.json"
        fi
        
        if [ ! -f "${MATRIX_FILE}" ]; then
          echo "::error::[VALIDATION_006] ${ACTION_NAME}: Matrix file not found: ${MATRIX_FILE}" >&2
          exit 1
        fi
        
        # Validate file has at least one enabled target
        if ! jq -e '.targets | length > 0' "${MATRIX_FILE}" >/dev/null 2>&1; then
          echo "::error::[VALIDATION_005] ${ACTION_NAME}: Matrix file must contain at least one enabled target" >&2
          exit 1
        fi
        
        # Export matrix file path for use in next step
        echo "MATRIX_FILE=${MATRIX_FILE}" >> "$GITHUB_ENV"
    
    - name: Check if PR images exist
      id: check
      shell: bash
      run: |
        set -e
        
        readonly ACTION_NAME="check-pr-images-exist"
        
        # Helper function: Sanitize branch name for Docker tag compatibility
        sanitize_branch() {
          local branch="$1"
          echo "${branch//\//-}"
        }
        
        # Helper function: Construct PR image tag
        construct_image_tag() {
          local repository="$1"
          local branch_sanitized="$2"
          local version="$3"
          local target_name="$4"
          local sha_short="$5"
          echo "ghcr.io/${repository}:pr-${branch_sanitized}-${version}-${target_name}-${sha_short}"
        }
        
        # Helper function: Check if image exists in GHCR
        image_exists() {
          local image_tag="$1"
          docker buildx imagetools inspect "${image_tag}" >/dev/null 2>&1
        }
        
        # Extract inputs
        REPOSITORY="${{ inputs.repository }}"
        BRANCH="${{ inputs.branch }}"
        VERSION="${{ inputs.version }}"
        PR_HEAD_SHA_SHORT="${{ inputs.pr_head_sha_short }}"
        
        # Matrix file was validated in previous step
        MATRIX_FILE="${MATRIX_FILE}"
        if [ ! -f "${MATRIX_FILE}" ]; then
          echo "::error::[VALIDATION_006] ${ACTION_NAME}: Matrix file not found: ${MATRIX_FILE}" >&2
          exit 1
        fi
        
        # Sanitize branch name
        BRANCH_SANITIZED=$(sanitize_branch "${BRANCH}")
        
        # Get all target names from matrix file (already filtered to only enabled targets)
        # No filtering needed - file already contains only enabled targets
        TARGET_NAMES=$(jq -r '.targets[].name' "${MATRIX_FILE}")
        TARGET_COUNT=$(jq '.targets | length' "${MATRIX_FILE}")
        
        echo "🔍 Checking ${TARGET_COUNT} PR image(s)..."
        
        # Check each target image
        ALL_FOUND=true
        MISSING_TARGETS=()
        
        while IFS= read -r target_name; do
          if [ -z "${target_name}" ]; then
            continue
          fi
          
          IMAGE_TAG=$(construct_image_tag "${REPOSITORY}" "${BRANCH_SANITIZED}" "${VERSION}" "${target_name}" "${PR_HEAD_SHA_SHORT}")
          
          if image_exists "${IMAGE_TAG}"; then
            echo "✅ Found PR image: ${IMAGE_TAG}"
          else
            echo "❌ PR image not found: ${IMAGE_TAG}"
            ALL_FOUND=false
            MISSING_TARGETS+=("${target_name}")
          fi
        done <<< "${TARGET_NAMES}"
        
        # Set output based on whether all images were found
        if [ "${ALL_FOUND}" = "true" ]; then
          PR_IMAGES_FOUND="true"
          echo ""
          echo "📊 Result: All ${TARGET_COUNT} PR image(s) found ✅"
        else
          PR_IMAGES_FOUND="false"
          echo ""
          echo "📊 Result: Missing ${#MISSING_TARGETS[@]} PR image(s): ${MISSING_TARGETS[*]} ❌"
        fi
        
        echo "pr_images_found=${PR_IMAGES_FOUND}" >> "$GITHUB_OUTPUT"
