name: 'Check PR Images Exist'
description: 'Check if PR images exist in GHCR'

inputs:
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  branch:
    description: 'Branch name'
    required: true
  version:
    description: 'Version string'
    required: true
  pr_head_sha_short:
    description: 'PR head SHA (short, 7 characters)'
    required: true
  matrix:
    description: 'JSON array of enabled targets'
    required: true

outputs:
  pr_images_found:
    description: 'Whether PR images exist (true/false)'
    value: ${{ steps.check.outputs.pr_images_found }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="check-pr-images-exist"
        
        # Validate all required inputs
        if [ -z "${{ inputs.repository }}" ] || [ "${{ inputs.repository }}" = "null" ] || [ "${{ inputs.repository }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: repository is required" >&2
          exit 1
        fi
        
        # Validate repository format (owner/repo)
        if ! [[ "${{ inputs.repository }}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
          echo "::error::[VALIDATION_004] ${ACTION_NAME}: Invalid repository format (expected: owner/repo)" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.branch }}" ] || [ "${{ inputs.branch }}" = "null" ] || [ "${{ inputs.branch }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: branch is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.version }}" ] || [ "${{ inputs.version }}" = "null" ] || [ "${{ inputs.version }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: version is required" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.pr_head_sha_short }}" ] || [ "${{ inputs.pr_head_sha_short }}" = "null" ] || [ "${{ inputs.pr_head_sha_short }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: pr_head_sha_short is required" >&2
          exit 1
        fi
        
        # Validate SHA short format (7 hex characters)
        if ! [[ "${{ inputs.pr_head_sha_short }}" =~ ^[a-f0-9]{7}$ ]]; then
          echo "::error::[VALIDATION_003] ${ACTION_NAME}: Invalid pr_head_sha_short format (expected: 7 hex characters)" >&2
          exit 1
        fi
        
        if [ -z "${{ inputs.matrix }}" ] || [ "${{ inputs.matrix }}" = "null" ] || [ "${{ inputs.matrix }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: matrix is required" >&2
          exit 1
        fi
        
        # Validate matrix is valid JSON
        if ! echo "${{ inputs.matrix }}" | jq empty 2>/dev/null; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: matrix must be valid JSON" >&2
          exit 1
        fi
    
    - name: Check if PR images exist
      id: check
      shell: bash
      run: |
        set -e
        
        REPOSITORY="${{ inputs.repository }}"
        BRANCH="${{ inputs.branch }}"
        VERSION="${{ inputs.version }}"
        PR_HEAD_SHA_SHORT="${{ inputs.pr_head_sha_short }}"
        MATRIX="${{ inputs.matrix }}"
        
        # Sanitize branch name
        BRANCH_SANITIZED="${BRANCH//\//-}"
        
        # Check if at least one PR image exists
        PR_IMAGES_FOUND="false"
        
        # Parse matrix JSON and check first target's PR image
        # The matrix is now passed as a proper JSON string from the workflow using toJson()
        FIRST_TARGET=$(echo "$MATRIX" | jq -r '.[0].name // empty' 2>/dev/null || echo "")
        
        if [ -n "${FIRST_TARGET}" ]; then
          PR_IMAGE_TAG="ghcr.io/${REPOSITORY}:pr-${BRANCH_SANITIZED}-${VERSION}-${FIRST_TARGET}-${PR_HEAD_SHA_SHORT}"
          echo "Checking for PR image: ${PR_IMAGE_TAG}"
          
          # Check if PR image exists (docker buildx imagetools inspect)
          if docker buildx imagetools inspect "${PR_IMAGE_TAG}" >/dev/null 2>&1; then
            echo "✓ Found PR image: ${PR_IMAGE_TAG}"
            PR_IMAGES_FOUND="true"
          else
            echo "✗ PR image not found: ${PR_IMAGE_TAG}"
          fi
        else
          echo "No targets found in matrix, assuming PR images not found"
          echo "Matrix value: ${MATRIX}"
          echo "Matrix length: ${#MATRIX}"
        fi
        
        echo "pr_images_found=${PR_IMAGES_FOUND}" >> $GITHUB_OUTPUT
        echo "PR images found: ${PR_IMAGES_FOUND}"

