name: 'Check PR Images Exist'
description: 'Check if PR images exist in GHCR'

inputs:
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  branch:
    description: 'Branch name'
    required: true
  version:
    description: 'Version string'
    required: true
  pr_head_sha_short:
    description: 'PR head SHA (short, 7 characters)'
    required: true
  matrix:
    description: 'JSON array of enabled targets'
    required: true

outputs:
  pr_images_found:
    description: 'Whether PR images exist (true/false)'
    value: ${{ steps.check.outputs.pr_images_found }}

runs:
  using: 'composite'
  steps:
    - name: Check if PR images exist
      id: check
      shell: bash
      run: |
        set -e
        
        REPOSITORY="${{ inputs.repository }}"
        BRANCH="${{ inputs.branch }}"
        VERSION="${{ inputs.version }}"
        PR_HEAD_SHA_SHORT="${{ inputs.pr_head_sha_short }}"
        MATRIX="${{ inputs.matrix }}"
        
        # #region agent log
        echo "{\"id\":\"log_$(date +%s)_check1\",\"timestamp\":$(date +%s)000,\"location\":\"check-pr-images-exist:39\",\"message\":\"Raw matrix input received\",\"data\":{\"matrixLength\":${#MATRIX},\"matrixPreview\":\"${MATRIX:0:200}\"},\"sessionId\":\"debug-session\",\"runId\":\"run1\",\"hypothesisId\":\"A\"}"
        # #endregion
        
        # Sanitize branch name
        BRANCH_SANITIZED="${BRANCH//\//-}"
        
        # Check if at least one PR image exists
        PR_IMAGES_FOUND="false"
        
        # Parse matrix JSON and check first target's PR image
        # The matrix might be passed with quotes, so we need to handle that
        # First, try to parse it directly
        # #region agent log
        JQ_ERROR=$(echo "$MATRIX" | jq . 2>&1 || true)
        echo "{\"id\":\"log_$(date +%s)_check2\",\"timestamp\":$(date +%s)000,\"location\":\"check-pr-images-exist:50\",\"message\":\"Initial jq parse attempt\",\"data\":{\"jqError\":\"$JQ_ERROR\",\"parseSuccess\":\"$([ -z \"$JQ_ERROR\" ] && echo true || echo false)\"},\"sessionId\":\"debug-session\",\"runId\":\"run1\",\"hypothesisId\":\"B\"}"
        # #endregion
        
        if ! echo "$MATRIX" | jq . >/dev/null 2>&1; then
          # If that fails, try removing surrounding quotes
          MATRIX_BEFORE="$MATRIX"
          MATRIX=$(echo "$MATRIX" | sed 's/^"//;s/"$//')
          # #region agent log
          echo "{\"id\":\"log_$(date +%s)_check3\",\"timestamp\":$(date +%s)000,\"location\":\"check-pr-images-exist:52\",\"message\":\"After quote removal\",\"data\":{\"beforeLength\":${#MATRIX_BEFORE},\"afterLength\":${#MATRIX},\"changed\":\"$([ \"$MATRIX_BEFORE\" != \"$MATRIX\" ] && echo true || echo false)\"},\"sessionId\":\"debug-session\",\"runId\":\"run1\",\"hypothesisId\":\"C\"}"
          # #endregion
          
          # Try parsing again after quote removal
          # #region agent log
          JQ_ERROR2=$(echo "$MATRIX" | jq . 2>&1 || true)
          echo "{\"id\":\"log_$(date +%s)_check4\",\"timestamp\":$(date +%s)000,\"location\":\"check-pr-images-exist:54\",\"message\":\"jq parse after quote removal\",\"data\":{\"jqError\":\"$JQ_ERROR2\",\"parseSuccess\":\"$([ -z \"$JQ_ERROR2\" ] && echo true || echo false)\"},\"sessionId\":\"debug-session\",\"runId\":\"run1\",\"hypothesisId\":\"C\"}"
          # #endregion
        fi
        
        # Extract first target name
        # #region agent log
        FIRST_TARGET=$(echo "$MATRIX" | jq -r '.[0].name // empty' 2>/dev/null || echo "")
        JQ_ERROR=$(echo "$MATRIX" | jq -r '.[0].name // empty' 2>&1 >/dev/null || echo "")
        echo "{\"id\":\"log_$(date +%s)_check5\",\"timestamp\":$(date +%s)000,\"location\":\"check-pr-images-exist:55\",\"message\":\"Extracting first target name\",\"data\":{\"firstTarget\":\"$FIRST_TARGET\",\"jqError\":\"${JQ_ERROR:0:200}\",\"hasError\":\"$([ -n \"$JQ_ERROR\" ] && echo true || echo false)\",\"isEmpty\":\"$([ -z \"$FIRST_TARGET\" ] && echo true || echo false)\"},\"sessionId\":\"debug-session\",\"runId\":\"run1\",\"hypothesisId\":\"D\"}"
        # #endregion
        
        if [ -n "${FIRST_TARGET}" ]; then
          PR_IMAGE_TAG="ghcr.io/${REPOSITORY}:pr-${BRANCH_SANITIZED}-${VERSION}-${FIRST_TARGET}-${PR_HEAD_SHA_SHORT}"
          echo "Checking for PR image: ${PR_IMAGE_TAG}"
          
          # Check if PR image exists (docker buildx imagetools inspect)
          if docker buildx imagetools inspect "${PR_IMAGE_TAG}" >/dev/null 2>&1; then
            echo "✓ Found PR image: ${PR_IMAGE_TAG}"
            PR_IMAGES_FOUND="true"
          else
            echo "✗ PR image not found: ${PR_IMAGE_TAG}"
          fi
        else
          echo "No targets found in matrix, assuming PR images not found"
          echo "Matrix value: ${MATRIX}"
          echo "Matrix length: ${#MATRIX}"
        fi
        
        echo "pr_images_found=${PR_IMAGES_FOUND}" >> $GITHUB_OUTPUT
        echo "PR images found: ${PR_IMAGES_FOUND}"

