name: 'Docker Build, Test, and Push'
description: 'Complete Docker build pipeline with setup, build, test, and push'

inputs:
  # Metadata inputs
  arch:
    description: 'Architecture (e.g., linux-amd64)'
    required: true
  repository:
    description: 'GitHub repository (e.g., owner/repo)'
    required: true
  branch:
    description: 'Branch name'
    required: true
  version:
    description: 'Version string'
    required: true
  target_name:
    description: 'Target name'
    required: true
  sha_short:
    description: 'Short commit SHA (7 characters)'
    required: false
  pr_mode:
    description: 'Whether to use PR tag format'
    required: false
    default: 'false'
  
  # Build args inputs
  builder_tag:
    description: 'Builder image tag'
    required: false
  builder_digest:
    description: 'Builder image digest'
    required: true
  base_tag:
    description: 'Base image tag'
    required: false
  base_digest:
    description: 'Base image digest'
    required: true
  build_date:
    description: 'Build date'
    required: false
  git_commit:
    description: 'Git commit SHA'
    required: true
  package_url:
    description: 'Package URL (optional)'
    required: false
  
  # Build config
  context:
    description: 'Docker build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  
  # Test config
  run_smoke_test:
    description: 'Whether to run smoke test'
    required: false
    default: 'false'
  test_url:
    description: 'Test URL endpoint to check (optional)'
    required: false
  
  # OCI Labels config
  include_oci_labels:
    description: 'Whether to include OCI labels in image'
    required: false
    default: 'false'
  sha:
    description: 'Full commit SHA (for OCI labels)'
    required: false
  server_url:
    description: 'GitHub server URL (for OCI labels)'
    required: false
  
  # Registry config
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Registry username'
    required: false
  password:
    description: 'Registry password/token (from secrets)'
    required: true

outputs:
  image-tag:
    description: 'Generated image tag'
    value: ${{ steps.metadata.outputs.image-tag }}
  platform:
    description: 'Platform string'
    value: ${{ steps.metadata.outputs.platform }}
  test-result:
    description: 'Smoke test result (if run)'
    value: ${{ steps.smoketest.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        set -e
        set -o pipefail
        
        ACTION_NAME="docker-build-test-push"
        
        # Validate required password input
        if [ -z "${{ inputs.password }}" ] || [ "${{ inputs.password }}" = "null" ] || [ "${{ inputs.password }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: password is required" >&2
          exit 1
        fi
        
        # Validate required dockerfile input
        if [ -z "${{ inputs.dockerfile }}" ] || [ "${{ inputs.dockerfile }}" = "null" ] || [ "${{ inputs.dockerfile }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: dockerfile is required" >&2
          exit 1
        fi
        
        # Validate required version input
        if [ -z "${{ inputs.version }}" ] || [ "${{ inputs.version }}" = "null" ] || [ "${{ inputs.version }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: version is required" >&2
          exit 1
        fi
        
        # Validate required arch input
        if [ -z "${{ inputs.arch }}" ] || [ "${{ inputs.arch }}" = "null" ] || [ "${{ inputs.arch }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: arch is required" >&2
          exit 1
        fi
        
        # Validate required repository input
        if [ -z "${{ inputs.repository }}" ] || [ "${{ inputs.repository }}" = "null" ] || [ "${{ inputs.repository }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: repository is required" >&2
          exit 1
        fi
        
        # Validate repository format (owner/repo)
        if ! [[ "${{ inputs.repository }}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
          echo "::error::[VALIDATION_004] ${ACTION_NAME}: Invalid repository format (expected: owner/repo)" >&2
          exit 1
        fi
        
        # Validate required branch input
        if [ -z "${{ inputs.branch }}" ] || [ "${{ inputs.branch }}" = "null" ] || [ "${{ inputs.branch }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: branch is required" >&2
          exit 1
        fi
        
        # Validate required target_name input
        if [ -z "${{ inputs.target_name }}" ] || [ "${{ inputs.target_name }}" = "null" ] || [ "${{ inputs.target_name }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: target_name is required" >&2
          exit 1
        fi
        
        # Validate required git_commit input
        if [ -z "${{ inputs.git_commit }}" ] || [ "${{ inputs.git_commit }}" = "null" ] || [ "${{ inputs.git_commit }}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: git_commit is required" >&2
          exit 1
        fi
        
        # Validate digests (required for Docker FROM statements)
        BUILDER_DIGEST="${{ inputs.builder_digest }}"
        BASE_DIGEST="${{ inputs.base_digest }}"
        if [ -z "${BUILDER_DIGEST}" ] || [ "${BUILDER_DIGEST}" = "null" ] || [ "${BUILDER_DIGEST}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: builder_digest is required" >&2
          exit 1
        fi
        if [ -z "${BASE_DIGEST}" ] || [ "${BASE_DIGEST}" = "null" ] || [ "${BASE_DIGEST}" = "" ]; then
          echo "::error::[VALIDATION_001] ${ACTION_NAME}: base_digest is required" >&2
          exit 1
        fi
        
        # Never log secret values
        echo "✓ Password provided (not logged)"
    
    # Setup (with QEMU)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3.12.0
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130  # v3.7.0
      with:
        image: tonistiigi/binfmt:qemu-v9.2.2
  
    # Login
    - name: Login to GHCR
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username || github.repository_owner }}
        password: ${{ inputs.password }}
  
    # Generate metadata (call existing action)
    - name: Generate metadata
      id: metadata
      uses: ./build-workflow/.github/actions/generate-metadata
      with:
        arch: ${{ inputs.arch }}
        repository: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        version: ${{ inputs.version }}
        target_name: ${{ inputs.target_name }}
        sha_short: ${{ inputs.sha_short }}
        pr_mode: ${{ inputs.pr_mode }}
  
    # Generate timestamp (if OCI labels enabled)
    - name: Generate timestamp
      id: timestamp
      if: inputs.include_oci_labels == 'true'
      uses: ./build-workflow/.github/actions/generate-timestamp
  
    # Prepare build args (call existing action)
    - name: Prepare build args
      id: prepare-build-args
      uses: ./build-workflow/.github/actions/prepare-build-args
      with:
        builder_tag: ${{ inputs.builder_tag }}
        builder_digest: ${{ inputs.builder_digest }}
        base_tag: ${{ inputs.base_tag }}
        base_digest: ${{ inputs.base_digest }}
        version: ${{ inputs.version }}
        build_date: ${{ inputs.build_date }}
        git_commit: ${{ inputs.git_commit }}
        package_url: ${{ inputs.package_url }}
  
    # Extract test URL (if needed for merge flow)
    - name: Extract test URL
      id: extract-test-url
      if: inputs.run_smoke_test == 'true' && (inputs.test_url == '' || inputs.test_url == 'null')
      uses: ./build-workflow/.github/actions/extract-version-metadata
      with:
        extract_test_url: 'true'
  
    # Prepare OCI labels (if enabled)
    - name: Prepare OCI labels
      id: prepare-labels
      if: inputs.include_oci_labels == 'true'
      shell: bash
      run: |
        {
          echo "org.opencontainers.image.created=${{ steps.timestamp.outputs.created }}"
          echo "org.opencontainers.image.title=${{ inputs.repository }}:${{ inputs.branch }}"
          echo "org.opencontainers.image.revision=${{ inputs.sha }}"
          echo "org.opencontainers.image.source=${{ inputs.server_url }}/${{ inputs.repository }}/tree/${{ inputs.branch }}"
          echo "org.opencontainers.image.vendor=${{ github.repository_owner }}"
          echo "org.opencontainers.image.version=${{ inputs.version }}"
        } > /tmp/oci-labels.txt
        {
          echo 'labels<<EOF'
          cat /tmp/oci-labels.txt
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
  
    # Build image
    - name: Build image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ steps.metadata.outputs.platform }}
        push: false
        load: true
        tags: ${{ steps.metadata.outputs.image-tag }}
        provenance: false
        build-args: ${{ steps.prepare-build-args.outputs.build_args }}
        labels: ${{ inputs.include_oci_labels == 'true' && steps.prepare-labels.outputs.labels || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
    # Smoke test (conditional)
    - name: Smoke Test
      id: smoketest
      if: inputs.run_smoke_test == 'true'
      uses: ./build-workflow/.github/actions/smoke-test
      with:
        image: ${{ steps.metadata.outputs.image-tag }}
        platform: ${{ steps.metadata.outputs.platform }}
        package_version: ${{ inputs.version }}
        test_url: ${{ inputs.test_url || steps.extract-test-url.outputs.test_url }}
  
    # Upload logs (conditional)
    - name: Upload test logs
      if: always() && inputs.run_smoke_test == 'true'
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
      with:
        name: test-logs-${{ inputs.target_name }}-${{ inputs.version }}
        path: ${{ inputs.version }}-test.log
        retention-days: 7
  
    # Push image
    - name: Push image
      if: success()
      shell: bash
      run: |
        docker push ${{ steps.metadata.outputs.image-tag }}

